import { createContext, useContext, useState, useEffect } from "react";

import HeydarAliyevCenter from "./assets/images/HeydarAliyevCenter.png";
import CarpetMuseumBaku from "./assets/images/Carpet.png";
import ArtMuseum from "./assets/images/ArtMuseum.png";
import MiniBook from "./assets/images/MiniBook.png";
import FireXram from "./assets/images/FireXram.png";
import NationalMusey from "./assets/images/NationalMusey.png";
import Literaturi from "./assets/images/LiteraturiMuseum.png";
import CentralMusei from "./assets/images/CentralMusei.png";
import IsteglalMusei from "./assets/images/IsteglalMusei.png";
import VurgunOlace from "./assets/images/Vurgunhouse.png";
import UzeirHouse from "./assets/images/UzeirHouse.png";
import JafarJabbarliHousem from "./assets/images/jafarjabbarlihousem.png";
import GanjaHistory from "./assets/images/GanjaHistory.png";
import MuzeyGandjs from "./assets/images/MuzeyGandjs.png";
import ShekiMuzet from "./assets/images/ShekiMuzey.png";
import WinterShekiMuzey from "./assets/images/WinterMuzey.png";
import ShekiMuzeyKravoed from "./assets/images/ShekiMuzeyKravoed.png";
import LankoranMuzey from "./assets/images/LankoranMuzey.png";
import LankoranHaziMuzey from "./assets/images/LankoranHaziHouseMuzey.png";
import ShamaxiMuzey from "./assets/images/ShamaxiMuzey.png";
import CarpetShusaMuzey from "./assets/images/CarpetShusaMuzey.png";
import MavzouleyShusa from "./assets/images/MouvsoleyShusha.png";
import BulBulMuzeyShusha from "./assets/images/BulBulMuzeyShusha.png";
import GabalaGeologCenter from "./assets/images/GabalaGeologCenter.png";
import GabalaArxelojiCenter from "./assets/images/GabalaArxelojiCenter.png";
import GabalaKraevodMuzey from "./assets/images/GabalaKraevodMuzey.png";
import XacmazMuzeum from "./assets/images/XacmazMuzeum.png";
import XacmazEzizEliyev from "./assets/images/ƏzizƏliyevMuzeyiXacmaz.png";
import MuzeumXacmaxfreinds from "./assets/images/MuzeumFreinds.png";
import XacmazCarpetMuzeum from "./assets/images/MuzeyCarpetXacmaz.png";
import ShamkirKraevodMuzey from "./assets/images/ShamkirKraevodMuzey.png";
import ShamkirFlagsMuzey from "./assets/images/ShamkirFlagsMuzey.png";
import LahicKraevodMuzey from "./assets/images/LahicKraevodMuzey.png";
import GazaxMuzey from "./assets/images/GazaxMuzey.png";
import YaratMusey from "./assets/images/YaratMuseum.png";

import HighPark from "./assets/images/BakuHigh.png";

// Atraction import

import SeeBreez from "./assets/images/SeeBreezActraction.png";
import SkyPark from "./assets/images/SkyParkActraction.png";
import VrPark from "./assets/images/VrParkAttractive.png";
import ShootingPark from "./assets/images/ShootingAttractive.png";
import Shagdag from "./assets/images/ShagdagAttractive.png";
import Safari from "./assets/images/SafariAttractive.png";
import HorseClub from "./assets/images/HorseClub.png";
import Gabalalnd from "./assets/images/QabalalandAtraction.png";
import Karting from "./assets/images/KartingBakuAttraction.png";
import Waterpark from "./assets/images/WaterparkAttraction.png";
import GanjaPaintBall from "./assets/images/GanjaPaintBallAtraction.png";
import GoyGolOffRoad from "./assets/images/GoyGolOffRoadAttraction.png";
import ZireZig from "./assets/images/ZireZipAttraction.png";
import GabalaShooting from "./assets/images/GabalaShootingAttraction.png";
import BakuClimbingGym from "./assets/images/ClimbingBakuAttraction.png";
import AquaParkNovyyLankaran from "./assets/images/LankaranAguaAtrraction.png";
import BakuEye from "./assets/images/BakuEyeAttraction.png";
import DalgaBeach from "./assets/images/DalgaBeachAttraction.png";
import Bowling from "./assets/images/BowlingAttraction.png";

import DescImg from "./assets/images/FCenter.png";
import DescFirstHeydar from "./assets/images/DescFirstHeydar.png";
import MiniAzer from "./assets/images/MiniAzer.png";
import MuzeyCaroet from "./assets/images/MuzeyCarpetdesc.png";
import MiniCarpet from "./assets/images/MiniCarpetDesc.png";
import MiniCarpet2 from "./assets/images/MiniCarpetDesc2.png";
import MuzeyArtMain from "./assets/images/MuzeyArtDesc.png";
import MuzeyArtMainItem from "./assets/images/MuzeyArtDescMainItem.png";
import MiniBookArtMain from "./assets/images/MiniBookMainDesc.png";
import MiniBookArtMainItem from "./assets/images/MiniBookArtMainItem.png";
import MiniBookArtMainItem2 from "./assets/images/MiniBookArtMainItem2.png";
import YaratMain from "./assets/images/YaratMain.png";
import YaratDesc from "./assets/images/YarartDesc.png";
import AteshgaxMain from "./assets/images/AteshgaxMain.png";
import AteshgaxDesc from "./assets/images/AteshgaxDescOpis.png";
import AteshgaxDesc2 from "./assets/images/AteshgaxDescOpis2.png";
import NationalMuseyMain from "./assets/images/NationalMuseyMain.png";
import NationalMuseyInside from "./assets/images/NationalMuseyDesc.png";
import NationalMuseyExtra from "./assets/images/NationalMuseyDesc2.png";
import LiteraturiMain from "./assets/images/MuseyNationalLiteraturiMain.png";
import LiteraturiInside from "./assets/images/MuseyNationalLiteraturidesc.png";
import LiteraturiExtra from "./assets/images/MuseyNationalLiteraturidesc2.png";
import CentralMuseiMain from "./assets/images/MuseumcenterMain.png";
import CentralMuseiInside from "./assets/images/MuseumcenterDesc.png";
import IsteglalMuseiMain from "./assets/images/IsteglalMuseiMain.png";
import IsteglalMuseiInside from "./assets/images/IsteglalMuseidesc.png";
import VurgunOlaceMain from "./assets/images/VurgunPLaceMain.png";
import VurgunOlaceInside from "./assets/images/VurgunPLaceDesc.png";
import HouseUzeirMuseumMain from "./assets/images/HouseUzeirMuseumDesc.png";
import HouseUzeirMuseumDesc from "./assets/images/HouseUzeirMuseumMain.png";
import HouseJafarbliMuseumMain from "./assets/images/jafarjabbarlihousemMain.png";
import HouseJafarbliMuseumDesc from "./assets/images/jafarjabbarlihousemdesc.png";
import GanjaHistoryMain from "./assets/images/GanjaHistoryMain.png";
import GanjaHistoryDesc from "./assets/images/GanjaHistoryDesc.png";
import GanjaMuseumMain from "./assets/images/MuzeyGandjsMain.png";
import GanjaMuseumDesc from "./assets/images/MuzeyGandjsDesc.png";
import ShamaxiMedrese from "./assets/images/ShamaxiCumaMedrese.png";
import ShamaxiMedreseMain from "./assets/images/ShamaxiCumaMedreseMain.png";
import ShamaxiMedreseDesc2 from "./assets/images/ShamaxiCumaMedreseDesc2.png";
import Diribaba from "./assets/images/DiriBabaNaxcivan.png";
import DiriBabaMain from "./assets/images/DiriBabaNaxcivanMain.png";
import DiriBabaDesc from "./assets/images/DiriBabaNaxcivanDesc.png";
import QobustanQorgu from "./assets/images/QobustanQorquMuzey.png";
import QobustanQorguMain from "./assets/images/QobustanQorquMuzeyMain.png";
import QobustanQorguDesc from "./assets/images/QobustanQorquMuzeyDesc.png";
import QobustanVolcano from "./assets/images/QobustanVulkan.png";
import QobustanVolcanoMain from "./assets/images/QobustanVulkanMain.png";
import QobustanVolcanoDesc from "./assets/images/QobustanVulkanDesc.png";
import ShekiWall from "./assets/images/ShekiDostopremecatelnost.png";
import ShekiWallMain from "./assets/images/ShekiDostopremecatelnostMain.png";
import ShekiWallDesc from "./assets/images/ShekiDostopremecatelnostDesc.png";
import SekiAlbani from "./assets/images/SekiAlbani.png";
import SekiAlbaniMain from "./assets/images/SekiAlbaniMain.png";
import SekiAlbaniDesc from "./assets/images/SekiAlbaniDesc.png";
import SekiXanMosque from "./assets/images/SekiXan.png";
import SekiXanMosqueMain from "./assets/images/SekiXanMain.png";
import SekiXanMosqueDesc from "./assets/images/SekiXanDesc.png";

// NATURE

import NohurLake from "./assets/images/NohurLakeNature.png";
import GoyGolLake from "./assets/images/GoyGolNature.png";
import IlisuVilage from "./assets/images/IlisuNature.png";
import LahicNature from "./assets/images/LahicNature.png";
import KarabaxNature from "./assets/images/KarabaxNation.png";
import LankaranNature from "./assets/images/LankaranGizilNature.png";
import YanardagNature from "./assets/images/YanardagNature.png";
import AfrudjaNature from "./assets/images/AfrudjaNature.png";
import QusarSuniNature from "./assets/images/QusarSuniNature.png";
import BeshbarmagNature from "./assets/images/BeshmarmagNature.png";
import QusarLazaNature from "./assets/images/QusarLazaNature.png";
import MaralgolNature from "./assets/images/MaralgolNature.png";
import QabalaNature from "./assets/images/QabalaYeddiNaature.png";
import QizilBashNature from "./assets/images/QizilbashNature.png";
import TangiyatiNature from "./assets/images/TanyagatiNature.png";

import NohurLakeMain from "./assets/images/NohurLakeMain.png";
import NohurLakeDesc from "./assets/images/NohurLakeDesc.png";
import GoyGolMain from "./assets/images/GoygolMain.png";
import GoyGolDesc from "./assets/images/GoygolDesc.png";
import IlisuMain from "./assets/images/IlisuMain.png";
import IlisuDesc from "./assets/images/IlisuDesc.png";
import LahicMain from "./assets/images/LahicMainNature.png";
import LahicDesc from "./assets/images/LahicDescNAature.png";
import KarabaxMain from "./assets/images/KarabaxMainNature.png";
import KarabaxDesc from "./assets/images/KarabaxDescNature.png";
import LankaranGizilMain from "./assets/images/LankaranGizilMain.png";
import LankaranGizilDesc from "./assets/images/LankaranGizilDesc.png";
import YanardagMainNature from "./assets/images/YanardagMainNature.png";
import YanardagDescNature from "./assets/images/YanarDagDescNature.png";
import AfrudjaMainNature from "./assets/images/AfrudjaMainNature.png";
import AfrudjaDescNature from "./assets/images/AfrudjaDescNature.png";
import QusarSuniMain from "./assets/images/QusarSuniMain.png";
import QusarSuinDesc from "./assets/images/QusarSuniDesc.png";
import BeshbarmagMainNature from "./assets/images/BeshmarmagNatureMain.png";
import BeshbarmagDescNature from "./assets/images/BeshmarmagDescNature.png";
import QusarLazaMainNature from "./assets/images/QusarLazaMainNAture.png";
import QusarLazaDescNature from "./assets/images/QusarLazaDescNature.png";
import MaralgolMainNature from "./assets/images/MaralgolMainNature.png";
import MaralgolDescNature from "./assets/images/MaralgolDescNature.png";
import QabalaYeddiMainNature from "./assets/images/QabalaYeddiMainNature.png";
import QabalaYeddiDescNature from "./assets/images/QabalaYeddiDescNature.png";
import QizilbashMainNature from "./assets/images/QizilbashMainNature.png";
import QizalbashDescNature from "./assets/images/QizilbashDescNature.png";
import TangiyatiMainNature from "./assets/images/TanyagatiMainNature.png";
import TangiyatiDescNature from "./assets/images/TanyagatiDescNature.png";

import HighParkMain from "./assets/images/HighParkMain.png";
import HighParkFunikler from "./assets/images/HighParkFunickler.png";
import SeeBreezMain from "./assets/images/SeeBreezMain.png";
import SeeBreezF from "./assets/images/SeeBreezF.png";
import SkyParkMain from "./assets/images/SkyParkMain.png";
import SkyParkZone from "./assets/images/SkyZone.png";
import VrParkMain from "./assets/images/VrParkMain.png";
import VrParkDesc from "./assets/images/VrParkDesc.png";
import ShootingMain from "./assets/images/ShootingMain.png";
import ShootingMainDesc from "./assets/images/ShootingMainDesc.png";
import ShootingMainDesc2 from "./assets/images/ShootingMainDesc2.png";
import ShagdagMain from "./assets/images/ShagdagMain.png";
import ShagdagMainDesc from "./assets/images/ShagdagMainDesc.png";
import ShagdagMainDesc2 from "./assets/images/ShagdagMainDesc2.png";
import SafariMain from "./assets/images/SafariMain.png";
import SafariMainDesc from "./assets/images/SafariMainDesc.png";
import SafariMainDesc2 from "./assets/images/SafariMainDesc2.png";
import HorseClubMain from "./assets/images/HorseClubMain.png";
import HorseClubDesc1 from "./assets/images/HorseClubDesc1.png";
import GabalalanfMain from "./assets/images/QabalalandMain.png";
import GabalalanfDesc from "./assets/images/QabalandDesc.png";
import KartingMain from "./assets/images/KartingMain.png";
import KartingDesc1 from "./assets/images/KartingDesc.png";
import WaterparkMain from "./assets/images/WaterparkMain.png";
import WaterparkDesc1 from "./assets/images/WaterparkDesc1.png";
import GanjaPaintMain from "./assets/images/GanjaPaintBallMain.png";
import GanjaPaintDesc from "./assets/images/GanjaPaintBallDesc.png";
import GoyGolOffRoadMain from "./assets/images/GoyGolOffRoadMain.png";
import GoyGolOffRoadDesc from "./assets/images/GoyGolOffRoadDesc.png";
import ZireZigMain from "./assets/images/ZireZipMain.png";
import ZireZigDesc from "./assets/images/ZireZipDesc.png";
import GabalaShootingMain from "./assets/images/GabalaShootingMain.png";
import GabalaShootingDesc from "./assets/images/GabalaShootingdesc.png";
import BakuClimbingGymMain from "./assets/images/BakuClimbingMain.png";
import BakuClimbingGymDesc from "./assets/images/BakuClimbingDesc.png";
import LankaranMain from "./assets/images/LankaranAguaMain.png";
import LankaranDesc from "./assets/images/LankaranAguaDesc.png";
import BakuEyeMain from "./assets/images/BakuEyeMain.png";
import BakuEyeDesc from "./assets/images/BakuEyeDesc.png";
import DalgaBeachMain from "./assets/images/DalgaBeachMain.png";
import DalgaBeachDesc from "./assets/images/DalgaBeachDesc.png";
import BowlingMain from "./assets/images/BowlingMain.png";
import BowlingDesc from "./assets/images/BowlingDesc.png";

import GS from "./ServicesProvidedComponent/asestss/GabalaSeason.png";
import NS from "./ServicesProvidedComponent/asestss/NabranSeason.png";
import SHS from "./ServicesProvidedComponent/asestss/ShekiSeason.png";

import SHW from "./ServicesProvidedComponent/asestss/SahdagWinter.png";
import TufWin from "./ServicesProvidedComponent/asestss/TufanWinter.png";
import HinWin from "./ServicesProvidedComponent/asestss/HinaligWinter.png";

import SS from "./ServicesProvidedComponent/asestss/ShekiSpring.png";
import SG from "./ServicesProvidedComponent/asestss/SpringGax.png";
import Ls from "./ServicesProvidedComponent/asestss/LerikSpring.png";

const MyContext = createContext();

export const MyProvider = ({ children }) => {
  const translations = {};

  const [punktMenu, setPunktMenu] = useState([]);

  const [point, setPointed] = useState();

  const [museums, setMuseums] = useState([]);

  const traveled = [
    {
      img: HeydarAliyevCenter,
      descImgMain: DescImg,
      DescFirstHeydar: DescFirstHeydar,
      DescSecondImg: MiniAzer,
      id: 1,
      name: "heydarAliyevCultureCenter",
      openClose: "openCloseHeydarAliyev",
      timeBuild: "timeBuildHeydarAliyev",
      adres: "adresHeydarAliyev",
      rooms: "roomsHeydarAliyev",
      sayt: "saytHeydarAliyev",
      category: "Bakıv",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryHeydarAliyev",
      minihistory2: "minihistory2HeydarAliyev",
      titleDescitemTop: "titleDescitemTopHeydarAliyev",
      titleDescitemTopOpis: "titleDescitemTopOpisHeydarAliyev",
      titleDescitemBottom: "titleDescitemBottomHeydarAliyev",
      titleDescitembottomOpis: "titleDescitemBottomOpisHeydarAliyev",
      position: [40.39614304461201, 49.86782382165357],
    },
    {
      img: CarpetMuseumBaku,
      descImgMain: MuzeyCaroet,
      DescFirstHeydar: MiniCarpet,
      DescSecondImg: MiniCarpet2,
      id: 2,
      name: "azerbaijanCarpetMuseum",
      openClose: "openCloseCarpetMuseum",
      timeBuild: "timeBuildCarpetMuseum",
      adres: "adresCarpetMuseum",
      rooms: "roomsCarpetMuseum",
      sayt: "saytCarpetMuseum",
      category: "Bakı",
      city: "baku",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryCarpetMuseum",
      minihistory2: "minihistory2CarpetMuseum",
      titleDescitemTop: "titleDescitemTopCarpetMuseum",
      titleDescitemTopOpis: "titleDescitemTopOpisCarpetMuseum",
      titleDescitemBottom: "titleDescitemBottomCarpetMuseum",
      titleDescitembottomOpis: "titleDescitemBottomOpisCarpetMuseum",
      position: [40.36006057581039, 49.835759424140555],
    },
    {
      img: ArtMuseum,
      descImgMain: MuzeyArtMain,
      DescFirstHeydar: MuzeyArtMainItem,
      id: 3,
      name: "artmuseumName",
      openClose: "artopenClose",
      timeBuild: "arttimeBuild",
      adres: "artadres",
      rooms: "artrooms",
      sayt: "artsayt",
      category: "Bakı",
      city: "baku",
      special: "museums",
      specialization: "Музей",
      minihistory: "artminihistory",
      minihistory2: "artminihistory2",
      titleDescitemTop: "arttitleDescitemTop",
      titleDescitemTopOpis: "arttitleDescitemTopOpis",
      position: [40.37817895990095, 49.864734698999804],
    },
    {
      img: MiniBook,
      descImgMain: MiniBookArtMain,
      DescFirstHeydar: MiniBookArtMainItem,
      DescSecondImg: MiniBookArtMainItem2,
      id: 4,
      name: "bakuMiniBookMuseum",
      openClose: "openCloseMiniBookMuseum",
      timeBuild: "timeBuildMiniBookMuseum",
      adres: "adresMiniBookMuseum",
      rooms: "roomsMiniBookMuseum",
      sayt: "saytMiniBookMuseum",
      category: "Bakı",
      city: "baku",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryMiniBookMuseum",
      minihistory2: "minihistory2MiniBookMuseum",
      titleDescitemTop: "titleDescitemTopMiniBookMuseum",
      titleDescitemTopOpis: "titleDescitemTopOpisMiniBookMuseum",
      titleDescitemBottom: "titleDescitemBottomMiniBookMuseum",
      titleDescitembottomOpis: "titleDescitemBottomOpisMiniBookMuseum",
      position: [40.36654555921063, 49.83269150084628],
    },
    {
      img: YaratMusey,
      descImgMain: YaratMain,
      DescFirstHeydar: YaratDesc,
      id: 5,
      special: "museums",
      name: "yaratContemporaryArt",
      openClose: "openCloseYarat",
      timeBuild: "timeBuildYarat",
      adres: "adresYarat",
      cost: "costYarat",
      rooms: "roomsYarat",
      sayt: "saytYarat",
      category: "Bakı",
      specialization: "Музей",
      minihistory: "minihistoryYarat1",
      minihistory2: "minihistoryYarat2",
      titleDescitemTop: "titleDescitemTopYarat",
      titleDescitemTopOpis: "titleDescitemTopOpisYarat",
      position: [40.33958794881875, 49.837389352975045],
    },
    {
      img: FireXram,
      descImgMain: AteshgaxMain,
      DescFirstHeydar: AteshgaxDesc,
      DescSecondImg: AteshgaxDesc2,
      id: 6,
      name: "fireTempleAteshgah",
      openClose: "openCloseFireTempleAteshgah",
      timeBuild: "timeBuildFireTempleAteshgah",
      adres: "adresFireTempleAteshgah",
      rooms: "roomsFireTempleAteshgah",
      sayt: "saytFireTempleAteshgah",
      category: "Bakı",
      city: "baku",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryFireTempleAteshgah",
      minihistory2: "minihistory2FireTempleAteshgah",
      titleDescitemTop: "titleDescitemTopFireTempleAteshgah",
      titleDescitemTopOpis: "titleDescitemTopOpisFireTempleAteshgah",
      titleDescitemBottom: "titleDescitemBottomFireTempleAteshgah",
      titleDescitembottomOpis: "titleDescitemBottomOpisFireTempleAteshgah",
      position: [40.41610108337718, 50.00915412783666],
    },
    {
      img: NationalMusey,
      descImgMain: NationalMuseyMain,
      DescFirstHeydar: NationalMuseyInside,
      DescSecondImg: NationalMuseyExtra,
      id: 7,
      name: "nationalMuseumHistoryAzerbaijan",
      openClose: "openCloseNationalMuseum",
      timeBuild: "timeBuildNationalMuseum",
      adres: "adresNationalMuseum",
      rooms: "roomsNationalMuseum",
      sayt: "saytNationalMuseum",
      category: "Bakı",
      city: "baku",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryNationalMuseum1",
      minihistory2: "minihistoryNationalMuseum2",
      titleDescitemTop: "titleDescitemTopNationalMuseum",
      titleDescitemTopOpis: "titleDescitemTopOpisNationalMuseum",
      titleDescitemBottom: "titleDescitemBottomNationalMuseum",
      titleDescitembottomOpis: "titleDescitemBottomOpisNationalMuseum",
      position: [40.3696695277519, 49.840055524140986],
    },
    {
      img: Literaturi,
      descImgMain: LiteraturiMain,
      DescFirstHeydar: LiteraturiInside,
      DescSecondImg: LiteraturiExtra,
      id: 8,
      name: "museumAzerbaijanLiterature",
      openClose: "openCloseLiteratureMuseum",
      timeBuild: "timeBuildLiteratureMuseum",
      adres: "adresLiteratureMuseum",
      rooms: "roomsLiteratureMuseum",
      sayt: "saytLiteratureMuseum",
      category: "Bakı",
      city: "baku",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryLiteratureMuseum1",
      minihistory2: "minihistoryLiteratureMuseum2",
      titleDescitemTop: "titleDescitemTopLiteratureMuseum",
      titleDescitemTopOpis: "titleDescitemTopOpisLiteratureMuseum",
      titleDescitemBottom: "titleDescitemBottomLiteratureMuseum",
      titleDescitembottomOpis: "titleDescitemBottomOpisLiteratureMuseum",
      position: [40.3699338121695, 49.8365194468696],
    },
    {
      img: CentralMusei,
      descImgMain: CentralMuseiMain,
      DescFirstHeydar: CentralMuseiInside,
      id: 9,
      name: "museumCenter",
      openClose: "openCloseMuseumCenter",
      timeBuild: "timeBuildMuseumCenter",
      adres: "adresMuseumCenter",
      rooms: "roomsMuseumCenter",
      sayt: "saytMuseumCenter",
      category: "Bakı",
      city: "baku",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryMuseumCenter1",
      minihistory2: "minihistoryMuseumCenter2",
      titleDescitemTop: "titleDescitemTopMuseumCenter",
      titleDescitemTopOpis: "titleDescitemTopOpisMuseumCenter",
      titleDescitemBottom: "titleDescitemBottomMuseumCenter",
      titleDescitembottomOpis: "titleDescitemBottomOpisMuseumCenter",
      position: [40.369669008238624, 49.843097552410285],
    },
    {
      img: IsteglalMusei,
      descImgMain: IsteglalMuseiMain,
      DescFirstHeydar: IsteglalMuseiInside,
      id: 10,
      name: "independenceMuseum",
      openClose: "openCloseIndependenceMuseum",
      timeBuild: "timeBuildIndependenceMuseum",
      adres: "adresIndependenceMuseum",
      rooms: "roomsIndependenceMuseum",
      sayt: "saytIndependenceMuseum",
      category: "Bakı",
      city: "baku",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryIndependenceMuseum1",
      minihistory2: "minihistoryIndependenceMuseum2",
      titleDescitemTop: "titleDescitemTopIndependenceMuseum",
      titleDescitemTopOpis: "titleDescitemTopOpisIndependenceMuseum",
      titleDescitemBottom: "titleDescitemBottomIndependenceMuseum",
      titleDescitembottomOpis: "titleDescitemBottomOpisIndependenceMuseum",
      position: [40.369751268695715, 49.842415867900364],
    },
    {
      img: VurgunOlace,
      descImgMain: VurgunOlaceMain,
      DescFirstHeydar: VurgunOlaceInside,
      id: 11,
      name: "samedVurghunHouseMuseum",
      openClose: "openCloseSamedVurghun",
      timeBuild: "timeBuildSamedVurghun",
      adres: "adresSamedVurghun",
      sayt: "saytSamedVurghun",
      category: "Bakı",
      city: "baku",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistorySamedVurghun1",
      minihistory2: "minihistorySamedVurghun2",
      titleDescitemTop: "titleDescitemTopSamedVurghun",
      titleDescitemTopOpis: "titleDescitemTopOpisSamedVurghun",
      position: [40.36891558760584, 49.83950495666997],
    },
    {
      img: UzeirHouse,
      descImgMain: HouseUzeirMuseumMain,
      DescFirstHeydar: HouseUzeirMuseumDesc,
      id: 12,
      specialization: "Музей",
      special: "museums",
      name: "uzeirName",
      openClose: "uzeirOpenClose",
      timeBuild: "uzeirTimeBuild",
      adres: "uzeirAdres",
      cost: "uzeirCost",
      rooms: "uzeirRooms",
      sayt: "uzeirSayt",
      category: "Bakı",
      minihistory: "uzeirMinihistory",
      minihistory2: "uzeirMinihistory2",
      titleDescitemTop: "uzeirTitleDescitemTop",
      titleDescitemTopOpis: "uzeirTitleDescitemTopOpis",
      position: [40.37756794921273, 49.829888768317566],
    },
    {
      img: JafarJabbarliHousem,
      descImgMain: HouseJafarbliMuseumMain,
      DescFirstHeydar: HouseJafarbliMuseumDesc,
      id: 13,
      specialization: "Музей",
      special: "museums",
      name: "JabbarliName",
      openClose: "JabbarliOpenClose",
      timeBuild: "JabbarliTimeBuild",
      adres: "JabbarliAdres",
      cost: "JabbarliCost",
      rooms: "JabbarliRooms",
      sayt: "JabbarliSayt",
      category: "Bakı",
      minihistory: "JabbarliMiniHistory1",
      minihistory2: "JabbarliMiniHistory2",
      titleDescitemTop: "JabbarliTitleDescTop",
      titleDescitemTopOpis: "JabbarliTitleDescOpis",
      position: [40.36800401727344, 49.82204186831723],
    },
    {
      img: GanjaHistory,
      descImgMain: GanjaHistoryMain,
      DescFirstHeydar: GanjaHistoryDesc,
      id: 14,
      specialization: "Музей",
      special: "museums",
      name: "GanjaHistoryName",
      openClose: "GanjaHistoryOpenClose",
      timeBuild: "GanjaHistoryTimeBuild",
      adres: "GanjaHistoryAdres",
      cost: "GanjaHistoryCost",
      rooms: "GanjaHistoryRooms",
      sayt: "GanjaHistorySayt",
      category: "Gəncə",
      minihistory: "GanjaHistoryMiniHistory1",
      minihistory2: "GanjaHistoryMiniHistory2",
      titleDescitemTop: "GanjaHistoryTitleDescTop",
      titleDescitemTopOpis: "GanjaHistoryTitleDescOpis",
      position: [40.68016505301273, 46.35785224318801],
    },
    {
      img: MuzeyGandjs,
      descImgMain: GanjaMuseumMain,
      DescFirstHeydar: GanjaMuseumDesc,
      id: 15,
      specialization: "Музей",
      special: "museums",
      name: "HeydarGanjaName",
      openClose: "HeydarGanjaOpenClose",
      timeBuild: "HeydarGanjaTimeBuild",
      adres: "HeydarGanjaAdres",
      cost: "HeydarGanjaCost",
      rooms: "HeydarGanjaRooms",
      sayt: "GanjaHistorySayt",
      category: "Gəncə",
      minihistory: "HeydarGanjaMiniHistory1",
      minihistory2: "HeydarGanjaMiniHistory2",
      titleDescitemTop: "HeydarGanjaTitleDescTop",
      titleDescitemTopOpis: "HeydarGanjaTitleDescOpis",
      position: [40.68082566225776, 46.36008225028516],
    },
    {
      img: ShekiMuzet,
      id: 16,
      specialization: "Музей",
      special: "museums",
      name: "ShekiPalaceName",
      openClose: "ShekiPalaceOpenClose",
      timeBuild: "ShekiPalaceTimeBuild",
      adres: "ShekiPalaceAdres",
      cost: "ShekiPalaceCost",
      rooms: "HeydarGanjaRooms",
      sayt: "ShekiPalaceSayt",
      category: "Şəki",
      minihistory: "ShekiPalaceMiniHistory1",
      minihistory2: "ShekiPalaceMiniHistory2",
      titleDescitemTop: "ShekiPalaceTitleDescTop",
      titleDescitemTopOpis: "ShekiPalaceTitleDescOpis",
      position: [41.20480551995459, 47.19760081730093],
    },
    {
      img: ShekiMuzeyKravoed,
      id: 17,
      specialization: "Музей",
      special: "Музей",
      name: "ShekiLocalMuseumName",
      openClose: "ShekiLocalMuseumOpenClose",
      timeBuild: "ShekiLocalMuseumTimeBuild",
      adres: "ShekiLocalMuseumAdres",
      cost: "ShekiLocalMuseumCost",
      rooms: "ShekiLocalMuseumRooms",
      sayt: "ShekiLocalMuseumSayt",
      category: "Şəki",
      minihistory: "ShekiLocalMuseumMiniHistory1",
      minihistory2: "ShekiLocalMuseumMiniHistory2",
      titleDescitemTop: "ShekiLocalMuseumTitleDescTop",
      titleDescitemTopOpis: "ShekiLocalMuseumTitleDescOpis",
      position: [41.203765764171216, 47.195549793492106],
    },
    {
      img: LankoranMuzey,
      id: 18,
      specialization: "Музей",
      special: "Музей",
      name: "LankoranHouseName",
      openClose: "LankoranHouseOpenClose",
      timeBuild: "LankoranHouseTimeBuild",
      adres: "LankoranHouseAdres",
      cost: "LankoranHouseCost",
      rooms: "LankoranHouseRooms",
      sayt: "LankoranHouseSayt",
      category: "Lənkəran",
      minihistory: "LankoranHouseMiniHistory1",
      minihistory2: "LankoranHouseMiniHistory2",
      titleDescitemTop: "LankoranHouseTitleDescTop",
      titleDescitemTopOpis: "LankoranHouseTitleDescOpis",
      position: [38.7540477963439, 48.856374136045645],
    },
    {
      img: LankoranHaziMuzey,
      id: 19,
      specialization: "Музей",
      special: "Музей",
      name: "LankoranAslanovHouseName",
      openClose: "LankoranAslanovHouseOpenClose",
      timeBuild: "LankoranAslanovHouseTimeBuild",
      adres: "LankoranAslanovHouseAdres",
      cost: "LankoranAslanovHouseCost",
      rooms: "LankoranAslanovHouseRooms",
      sayt: "LankoranHouseSayt",
      category: "Lənkəran",
      minihistory: "LankoranAslanovHouseMiniHistory1",
      minihistory2: "LankoranAslanovHouseMiniHistory2",
      titleDescitemTop: "LankoranAslanovHouseTitleDescTop",
      titleDescitemTopOpis: "LankoranAslanovHouseTitleDescOpis",
      position: [38.750439991815405, 48.851898483219735],
    },
    {
      img: ShamaxiMuzey,
      id: 20,
      specialization: "Музей",
      special: "Музей",
      name: "observatoryName",
      openClose: "observatoryOpenClose",
      timeBuild: "observatoryTimeBuild",
      adres: "observatoryAdres",
      cost: "-",
      rooms: "observatoryRooms",
      sayt: "observatorySayt",
      category: "Şamaxı",
      minihistory: "observatoryMinihistory",
      minihistory2: "observatoryMinihistory2",
      titleDescitemTop: "observatoryTitleDescitemTop",
      titleDescitemTopOpis: "observatoryTitleDescitemTopOpis",
      position: [40.782206809956854, 48.60034001250998],
    },
    {
      img: CarpetShusaMuzey,
      id: 21,
      specialization: "Музей",
      special: "Музей",
      name: "carpetShusaName",
      openClose: "carpetShusaOpenClose",
      timeBuild: "carpetShusaTimeBuild",
      adres: "carpetShusaAdres",
      cost: "carpetShusaCost",
      rooms: "carpetShusaRooms",
      sayt: "LankoranHouseSayt",
      category: "Qarabağ",
      minihistory: "carpetShusaMinihistory",
      minihistory2: "carpetShusaMinihistory2",
      titleDescitemTop: "carpetShusaTitleDescitemTop",
      titleDescitemTopOpis: "carpetShusaTitleDescitemTopOpis",
      position: [39.76014783752609, 46.747271666446544],
    },
    {
      img: MavzouleyShusa,
      id: 22,
      special: "palaces",
      specialization: "Дворцы",
      name: "vagifName",
      openClose: "vagifOpenClose",
      timeBuild: "vagifTimeBuild",
      adres: "vagifAdres",
      cost: "vagifCost",
      rooms: "vagifRooms",
      sayt: "LankoranHouseSayt",
      category: "Qarabağ",
      minihistory: "vagifMinihistory",
      minihistory2: "vagifMinihistory2",
      titleDescitemTop: "vagifTitleDescitemTop",
      titleDescitemTopOpis: "vagifTitleDescitemTopOpis",
      position: [39.75555149710669, 46.75828118178732],
    },
    {
      img: BulBulMuzeyShusha,
      id: 23,
      specialization: "Музей",
      special: "Музей",
      name: "bulbulName",
      openClose: "bulbulOpenClose",
      timeBuild: "bulbulTimeBuild",
      adres: "bulbulAdres",
      cost: "bulbulCost",
      rooms: "bulbulRooms",
      sayt: "-",
      category: "Qarabağ",
      minihistory: "bulbulMinihistory",
      minihistory2: "bulbulMinihistory2",
      titleDescitemTop: "bulbulTitleDescitemTop",
      titleDescitemTopOpis: "bulbulTitleDescitemTopOpis",
      position: [40.37396883760093, 49.84409356036397],
    },
    {
      img: GabalaGeologCenter,
      id: 24,
      specialization: "Музей",
      special: "Музей",
      name: "gabalaName",
      openClose: "gabalaOpenClose",
      timeBuild: "gabalaTimeBuild",
      adres: "gabalaAdres",
      cost: "gabalaCost",
      rooms: "bulbulRooms",
      category: "Qəbələ",
      minihistory: "gabalaMinihistory",
      minihistory2: "gabalaMinihistory2",
      titleDescitemTop: "gabalaTitleDescitemTop",
      titleDescitemTopOpis: "gabalaTitleDescitemTopOpis",
      position: [40.88956569220364, 47.693500750163025],
    },
    {
      img: GabalaArxelojiCenter,
      id: 25,
      specialization: "Музей",
      special: "Музей",
      name: "gabalaBulbulName",
      openClose: "gabalaBulbulOpenClose",
      timeBuild: "gabalaBulbulTimeBuild",
      adres: "gabalaBulbulAdres",
      cost: "gabalaBulbulCost",
      rooms: "gabalaBulbulRooms",
      category: "Qəbələ",
      minihistory: "gabalaBulbulMinihistory",
      minihistory2: "gabalaBulbulMinihistory2",
      titleDescitemTop: "gabalaBulbulTitleDescitemTop",
      titleDescitemTopOpis: "gabalaBulbulTitleDescitemTopOpis",
      position: [39.791805338883194, 46.74363695507068],
    },
    {
      img: GabalaKraevodMuzey,
      id: 26,
      specialization: "Музей",
      special: "Музей",
      name: "gabalaKraevoName",
      openClose: "gabalaKraevoOpenClose",
      timeBuild: "gabalaKraevoTimeBuild",
      adres: "gabalaKraevoAdres",
      cost: "gabalaKraevoCost",
      rooms: "gabalaKraevoRooms",
      category: "Qəbələ",
      minihistory: "gabalaKraevoMinihistory",
      minihistory2: "gabalaKraevoMinihistory2",
      titleDescitemTop: "gabalaKraevoTitleDescitemTop",
      titleDescitemTopOpis: "gabalaKraevoTitleDescitemTopOpis",
      position: [39.76014783752609, 46.747271666446544],
    },
    {
      img: XacmazMuzeum,
      id: 27,
      specialization: "Музей",
      special: "Музей",
      name: "xachmazName",
      openClose: "xachmazOpenClose",
      timeBuild: "xachmazTimeBuild",
      adres: "xachmazAdres",
      cost: "xachmazCost",
      rooms: "xachmazRooms",
      category: "Xaçmaz",
      minihistory: "xachmazMinihistory",
      minihistory2: "xachmazMinihistory2",
      titleDescitemTop: "xachmazTitleDescitemTop",
      titleDescitemTopOpis: "xachmazTitleDescitemTopOpis",
      position: [41.465667598880366, 48.805482435340465],
    },
    {
      img: XacmazEzizEliyev,
      id: 28,
      specialization: "Музей",
      special: "Музей",
      name: "xachmazAliyevName",
      openClose: "xachmazAliyevOpenClose",
      timeBuild: "xachmazAliyevTimeBuild",
      adres: "xachmazAliyevAdres",
      cost: "xachmazAliyevCost",
      rooms: "xachmazAliyevRooms",
      category: "Xaçmaz",
      minihistory: "xachmazAliyevMinihistory",
      minihistory2: "xachmazAliyevMinihistory2",
      titleDescitemTop: "xachmazAliyevTitleDescitemTop",
      titleDescitemTopOpis: "xachmazAliyevTitleDescitemTopOpis",
      position: [41.46444555578588, 48.80160932580804],
    },
    {
      img: MuzeumXacmaxfreinds,
      id: 29,
      specialization: "Музей",
      special: "Музей",
      name: "xachmazFriendsName",
      openClose: "xachmazFriendsOpenClose",
      timeBuild: "xachmazFriendsTimeBuild",
      adres: "xachmazFriendsAdres",
      cost: "xachmazFriendsCost",
      rooms: "xachmazFriendsRooms",
      category: "Xaçmaz",
      minihistory: "xachmazFriendsMinihistory",
      minihistory2: "xachmazFriendsMinihistory2",
      titleDescitemTop: "xachmazFriendsTitleDescitemTop",
      titleDescitemTopOpis: "xachmazFriendsTitleDescitemTopOpis",
      position: [41.465843287872325, 48.805422234720055],
    },
    {
      img: XacmazCarpetMuzeum,
      id: 30,
      specialization: "Музей",
      special: "Музей",
      name: "xachmazCarpetName",
      openClose: "xachmazCarpetOpenClose",
      timeBuild: "xachmazCarpetTimeBuild",
      adres: "xachmazCarpetAdres",
      cost: "xachmazCarpetCost",
      rooms: "xachmazCarpetRooms",
      category: "Xaçmaz",
      minihistory: "xachmazCarpetMinihistory",
      minihistory2: "xachmazCarpetMinihistory2",
      titleDescitemTop: "xachmazCarpetTitleDescitemTop",
      titleDescitemTopOpis: "xachmazCarpetTitleDescitemTopOpis",
      position: [41.465192072170105, 48.800696182783675],
    },
    {
      img: ShamkirKraevodMuzey,
      id: 31,
      specialization: "Музей",
      special: "Музей",
      name: "shamkirKraevoName",
      openClose: "shamkirKraevoOpenClose",
      timeBuild: "shamkirKraevoTimeBuild",
      adres: "shamkirKraevoAdres",
      cost: "shamkirKraevoCost",
      rooms: "xachmazCarpetRooms",
      category: "Şəmkir",
      minihistory: "shamkirKraevoMinihistory",
      minihistory2: "shamkirKraevoMinihistory2",
      titleDescitemTop: "shamkirKraevoTitleDescitemTop",
      titleDescitemTopOpis: "shamkirKraevoTitleDescitemTopOpis",
      position: [40.833590426646936, 46.02476710296071],
    },
    {
      img: ShamkirFlagsMuzey,
      id: 32,
      specialization: "Музей",
      special: "Музей",
      name: "Музей флага",
      openClose: "вт-вс 9:00–17:00",
      timeBuild: "9 ноября 2010 года",
      adres: "Shamkir, Азербайджан",
      rooms: "Количество выставочных залов: 5",
      sayt: "-",
      category: "Şəmkir",
      position: [40.853776409610894, 46.03603171284904],
    },
    {
      img: LahicKraevodMuzey,
      id: 33,
      specialization: "Музей",
      special: "Музей",
      name: "Историко-краеведческий музей Лагича",
      openClose: "вт-вс 9:00–17:00",
      timeBuild: "в 1985 году",
      adres: "Исмаиллинском районе Азербайджана",
      rooms: "Количество выставочных залов: 5",
      sayt: "-",
      category: "Ismayilli",
      position: [40.84539355851624, 48.38338012970039],
    },
    {
      img: GazaxMuzey,
      id: 34,
      specialization: "Музей",
      special: "Музей",
      name: "Историко-Краеведческий Музей Газахского района",
      openClose: "вт-вс 9:00–17:00",
      timeBuild: "в 1984 году.",
      // 19 октября 2016 года
      adres: "Гейдар Алиев, Газах",
      rooms: "Количество выставочных залов: 5",
      sayt: "-",
      category: "Qarışıq yerlər",
      position: [41.09099669016063, 45.36158940328703],
    },
    // Attractive
    // Attractive Baku
    {
      img: SeeBreez,
      descImgMain: SeeBreezMain,
      DescFirstHeydar: SeeBreezF,
      id: 35,
      special: "Attractive",
      specialization: "Attractive",
      name: "seaBreeze",
      openClose: "openCloseSeaBreeze",
      timeBuild: "timeBuildSeaBreeze",
      adres: "adresSeaBreeze",
      // cost: "-",
      // rooms: "roomsSeaBreeze",
      sayt: "saytSeaBreeze",
      category: "Bakı",
      minihistory: "minihistorySeaBreeze",
      minihistory2: "minihistory2SeaBreeze",
      position: [40.582312074926946, 49.94406779295458],
      titleDescitemTop: "titleDescitemTopSeaBreeze",
      titleDescitemTopOpis: "titleDescitemTopOpisSeaBreeze",
    },
    {
      img: SkyPark,
      descImgMain: SkyParkMain,
      DescFirstHeydar: SkyParkZone,
      id: 36,
      name: "SkyPark",
      openClose: "openCloseSkyPark",
      timeBuild: "timeBuildSkyPark",
      adres: "adresSkyPark",
      cost: "costSkyPark",
      rooms: "roomsSkyPark",
      sayt: "saytSkyPark",
      category: "Bakı",
      city: "baku",
      special: "attractive",
      specialization: "Attractive",
      minihistory: "minihistorySkyPark1",
      minihistory2: "minihistorySkyPark2",
      titleDescitemTop: "titleDescitemTopSkyPark",
      titleDescitemTopOpis: "titleDescitemTopOpisSkyPark",
      position: [40.35818252243587, 49.83753617016377],
    },
    {
      img: VrPark,
      descImgMain: VrParkMain,
      DescFirstHeydar: VrParkDesc,
      id: 37,
      name: "vrPark",
      openClose: "openCloseVRPark",
      timeBuild: "timeBuildVRPark",
      adres: "adresVRPark",
      cost: "20–27 AZN",
      // rooms: "roomsSkyPark",
      sayt: "saytVRPark",
      category: "Bakı",
      city: "baku",
      special: "attractive",
      specialization: "Attractive",
      minihistoryVRPark1: "minihistorySkyPark1",
      minihistoryVRPark2: "minihistorySkyPark2",
      titleDescitemTopVRPark: "titleDescitemTopSkyPark",
      titleDescitemTopOpisVRPark: "titleDescitemTopOpisSkyPark",
      position: [40.378783490431765, 49.87593738550576],
    },
    {
      img: ShootingPark,
      descImgMain: ShootingMain,
      DescFirstHeydar: ShootingMainDesc,
      DescSecondImg: ShootingMainDesc2,
      id: 38,
      special: "Attractive",
      specialization: "Attractive",
      name: "nameBakuShooting",
      openClose: "openCloseBakuShooting",
      timeBuild: "timeBuildBakuShooting",
      adres: "adresBakuShooting",
      cost: "costBakuShooting",
      rooms: "roomsBakuShooting",
      sayt: "-",
      category: "Bakı",
      minihistory: "minihistoryBakuShooting1",
      minihistory2: "minihistoryBakuShooting2",
      titleDescitemTop: "titleDescitemTopBakuShooting",
      titleDescitemTopOpis: "titleDescitemTopOpisBakuShooting",
      titleDescitemBottom: "titleDescitemBottom",
      titleDescitembottomOpis: "titleDescitembottomOpis",
      position: [40.41335624664135, 49.790497324142756],
    },
    {
      img: HorseClub,
      descImgMain: HorseClubMain,
      DescFirstHeydar: HorseClubDesc1,
      id: 39,
      special: "Attractive",
      specialization: "Attractive",
      name: "HorseClubname",
      openClose: "openCloseHorseClub",
      timeBuild: "timeBuildHorseClub",
      adres: "adresHorseClub",
      cost: "costHorseClub",
      rooms: "roomsHorseClub",
      sayt: "-",
      category: "Bakı",
      minihistory: "minihistoryHorseClub1",
      minihistory2: "minihistoryHorseClub2",
      titleDescitemTop: "titleDescitemTopHorseClub",
      titleDescitemTopOpis: "titleDescitemTopOpisHorseClub",
      position: [40.465268896411345, 50.084903275708484],
    },
    {
      img: Karting,
      descImgMain: KartingMain,
      DescFirstHeydar: KartingDesc1,
      id: 40,
      special: "Attractive",
      specialization: "Attractive",
      name: "KartingName",
      openClose: "KartingOpenClose",
      timeBuild: "KartingTimeBuild",
      adres: "KartingAdres",
      cost: "KartingCost",
      rooms: "KartingRooms",
      sayt: "KartingSayt",
      category: "Bakı",
      minihistory: "KartingMiniHistory1",
      minihistory2: "KartingMiniHistory2",
      titleDescitemTop: "KartingTitleDescTop",
      titleDescitemTopOpis: "KartingTitleDescOpis",
      position: [40.4197524673782, 49.854258539483936],
    },
    {
      img: Waterpark,
      descImgMain: WaterparkMain,
      DescFirstHeydar: WaterparkDesc1,
      id: 41,
      special: "Attractive",
      specialization: "Attractive",
      name: "WaterparkName",
      openClose: "WaterparkOpenClose",
      timeBuild: "WaterparkTimeBuild",
      adres: "WaterparkAdres",
      cost: "WaterparkCost",
      rooms: "WaterparkRooms",
      sayt: "WaterparkSayt",
      category: "Bakı",
      minihistory: "WaterparkMiniHistory1",
      minihistory2: "WaterparkMiniHistory2",
      titleDescitemTop: "WaterparkTitleDescTop",
      titleDescitemTopOpis: "WaterparkTitleDescOpis",
      position: [40.5896431467394, 50.06437546320031],
    },
    {
      img: ZireZig,
      descImgMain: ZireZigMain,
      DescFirstHeydar: ZireZigDesc,
      id: 42,
      special: "Attractive",
      specialization: "Attractive",
      name: "ZireExtremeName",
      openClose: "ZireExtremeOpenClose",
      timeBuild: "ZireExtremeTimeBuild",
      adres: "ZireExtremeAdres",
      cost: "ZireExtremeCost",
      rooms: "ZireExtremeRooms",
      sayt: "ZireExtremeSayt",
      category: "Bakı",
      minihistory: "ZireExtremeMinihistory",
      minihistory2: "ZireExtremeMinihistory2",
      titleDescitemTop: "ZireExtremeTitleDescitemTop",
      titleDescitemTopOpis: "ZireExtremeTitleDescitemTopOpis",
      position: [40.40860629815081, 50.29764468764973],
    },
    {
      img: BakuClimbingGym,
      descImgMain: BakuClimbingGymMain,
      DescFirstHeydar: BakuClimbingGymDesc,
      id: 43,
      special: "Attractive",
      specialization: "Attractive",
      name: "ClimbingGymName",
      openClose: "ClimbingGymOpenClose",
      timeBuild: "ClimbingGymTimeBuild",
      adres: "ClimbingGymAdres",
      cost: "ClimbingGymCost",
      rooms: "ClimbingGymRooms",
      sayt: "ClimbingGymSayt",
      category: "Bakı",
      minihistory: "ClimbingGymMinihistory",
      minihistory2: "ClimbingGymMinihistory2",
      titleDescitemTop: "ClimbingGymTitleDescitemTop",
      titleDescitemTopOpis: "ClimbingGymTitleDescitemTopOpis",
      position: [40.37820114060415, 49.89823211618776],
    },
    {
      img: BakuEye,
      descImgMain: BakuEyeMain,
      DescFirstHeydar: BakuEyeDesc,
      id: 44,
      special: "Attractive",
      specialization: "Attractive",
      name: "BakuEyeName",
      openClose: "BakuEyeOpenClose",
      timeBuild: "BakuEyeTimeBuild",
      adres: "BakuEyeAdres",
      cost: "BakuEyeCost",
      rooms: "BakuEyeRooms",
      sayt: "BakuEyeSayt",
      category: "Bakı",
      minihistory: "BakuEyeMinihistory",
      minihistory2: "BakuEyeMinihistory2",
      titleDescitemTop: "BakuEyeTitleDescitemTop",
      titleDescitemTopOpis: "BakuEyeTitleDescitemTopOpis",
      position: [40.35478258605121, 49.83763892783404],
    },
    {
      img: DalgaBeach,
      descImgMain: DalgaBeachMain,
      DescFirstHeydar: DalgaBeachDesc,
      id: 45,
      special: "Attractive",
      specialization: "Attractive",
      name: "DalgaBeachName",
      openClose: "DalgaBeachOpenClose",
      timeBuild: "DalgaBeachTimeBuild",
      adres: "DalgaBeachAdres",
      cost: "DalgaBeachCost",
      rooms: "DalgaBeachRooms",
      sayt: "DalgaBeachSayt",
      category: "Bakı",
      minihistory: "DalgaBeachMinihistory",
      minihistory2: "DalgaBeachMinihistory2",
      titleDescitemTop: "DalgaBeachTitleDescitemTop",
      titleDescitemTopOpis: "DalgaBeachTitleDescitemTopOpis",
      position: [40.51227922076515, 50.16744499900515],
    },
    {
      img: Bowling,
      descImgMain: BowlingMain,
      DescFirstHeydar: BowlingDesc,
      id: 46,
      special: "Attractive",
      specialization: "Attractive",
      name: "BowlingName",
      openClose: "BowlingOpenClose",
      timeBuild: "BowlingTimeBuild",
      adres: "BowlingAdres",
      cost: "BowlingCost",
      rooms: "BowlingRooms",
      sayt: "BowlingSayt",
      category: "Bakı",
      minihistory: "BowlingMinihistory",
      minihistory2: "BowlingMinihistory2",
      titleDescitemTop: "BowlingTitleDescitemTop",
      titleDescitemTopOpis: "BowlingTitleDescitemTopOpis",
      position: [40.37691787789518, 49.84130423353565],
    },
    // Attractive Qusar
    {
      img: Shagdag,
      descImgMain: ShagdagMain,
      DescFirstHeydar: ShagdagMainDesc,
      DescSecondImg: ShagdagMainDesc2,
      id: 47,
      special: "Attractive",
      specialization: "Attractive",
      name: "ShahdagName",
      openClose: "ShahdagOpenClose",
      timeBuild: "ShahdagTimeBuild",
      adres: "ShahdagAdres",
      cost: "ShahdagCost",
      rooms: "ShahdagRooms",
      sayt: "ShahdagSayt",
      category: "Qusar",
      minihistory: "ShahdagMinihistory",
      minihistory2: "ShahdagMinihistory2",
      titleDescitemTop: "ShahdagTitleDescitemTop",
      titleDescitemTopOpis: "ShahdagTitleDescitemTopOpis",
      titleDescitemBottom: "ShahdagTitleDescitemBottom",
      titleDescitembottomOpis: "ShahdagTitleDescitemBottomOpis",
      position: [40.07626112747628, 49.414580184785265],
    },
    // Attractive Qobustan
    {
      img: Safari,
      descImgMain: SafariMain,
      DescFirstHeydar: SafariMainDesc,
      DescSecondImg: SafariMainDesc2,
      id: 48,
      special: "Attractive",
      specialization: "Attractive",
      name: "QobustanSafariName",
      openClose: "QobustanSafariOpenClose",
      timeBuild: "QobustanSafariTimeBuild",
      adres: "QobustanSafariAdres",
      cost: "QobustanSafariCost",
      rooms: "QobustanSafariRooms",
      sayt: "QobustanSafariSayt",
      category: "Qobustan",
      minihistory: "QobustanSafariMinihistory",
      minihistory2: "QobustanSafariMinihistory2",
      titleDescitemTop: "QobustanSafariTitleDescitemTop",
      titleDescitemTopOpis: "QobustanSafariTitleDescitemTopOpis",
      titleDescitemBottom: "QobustanSafariTitleDescitemBottom",
      titleDescitembottomOpis: "QobustanSafariTitleDescitemBottomOpis",
      position: [41.00252455558901, 47.87817116649553],
    },
    // Attractive Qabala
    {
      img: Gabalalnd,
      descImgMain: GabalalanfMain,
      DescFirstHeydar: GabalalanfDesc,
      id: 49,
      special: "Attractive",
      specialization: "Attractive",
      name: "GabalandName",
      openClose: "GabalandOpenClose",
      timeBuild: "GabalandTimeBuild",
      adres: "GabalandAdres",
      cost: "GabalandCost",
      rooms: "GabalandRooms",
      sayt: "GabalandSayt",
      category: "Qəbələ",
      minihistory: "GabalandMinihistory",
      minihistory2: "GabalandMinihistory2",
      titleDescitemTop: "GabalandTitleDescitemTop",
      titleDescitemTopOpis: "GabalandTitleDescitemTopOpis",
      position: [41.00252455558901, 47.87817116649553],
    },
    {
      img: GabalaShooting,
      descImgMain: GabalaShootingMain,
      DescFirstHeydar: GabalaShootingDesc,
      id: 50,
      special: "Attractive",
      specialization: "Attractive",
      name: "GabalaShootingName",
      openClose: "GabalaShootingOpenClose",
      timeBuild: "GabalaShootingTimeBuild",
      adres: "GabalaShootingAdres",
      cost: "GabalaShootingCost",
      rooms: "GabalaShootingRooms",
      sayt: "GabalaShootingSayt",
      category: "Qəbələ",
      minihistory: "GabalaShootingMinihistory",
      minihistory2: "GabalaShootingMinihistory2",
      titleDescitemTop: "GabalaShootingTitleDescitemTop",
      titleDescitemTopOpis: "GabalaShootingTitleDescitemTopOpis",
      position: [41.00458134752198, 47.80124223766034],
    },
    // Attraction Ganja
    {
      img: GanjaPaintBall,
      descImgMain: GanjaPaintMain,
      DescFirstHeydar: GanjaPaintDesc,
      id: 51,
      special: "Attractive",
      specialization: "Attractive",
      name: "GanjaPaintballName",
      openClose: "GanjaPaintballOpenClose",
      timeBuild: "GanjaPaintballTimeBuild",
      adres: "GanjaPaintballAdres",
      cost: "GanjaPaintballCost",
      rooms: "GanjaPaintballRooms",
      sayt: "GanjaPaintballSayt",
      category: "Gəncə",
      minihistory: "GanjaPaintballMinihistory",
      minihistory2: "GanjaPaintballMinihistory2",
      titleDescitemTop: "GanjaPaintballTitleDescitemTop",
      titleDescitemTopOpis: "GanjaPaintballTitleDescitemTopOpis",
      position: [40.683722379060875, 46.402058956682424],
    },
    // Attraction Goygol
    {
      img: GoyGolOffRoad,
      descImgMain: GoyGolOffRoadMain,
      DescFirstHeydar: GoyGolOffRoadDesc,
      id: 52,
      special: "Attractive",
      specialization: "Attractive",
      name: "GoygolOffRoadName",
      openClose: "GoygolOffRoadOpenClose",
      timeBuild: "GoygolOffRoadTimeBuild",
      adres: "GoygolOffRoadAdres",
      cost: "GoygolOffRoadCost",
      rooms: "GoygolOffRoadRooms",
      sayt: "GoygolOffRoadSayt",
      category: "Gəncə",
      minihistory: "GoygolOffRoadMinihistory",
      minihistory2: "GoygolOffRoadMinihistory2",
      titleDescitemTop: "GoygolOffRoadTitleDescitemTop",
      titleDescitemTopOpis: "GoygolOffRoadTitleDescitemTopOpis",
      position: [40.58692241910394, 46.315861141337464],
    },
    // Attraction Lankaran
    {
      img: AquaParkNovyyLankaran,
      descImgMain: LankaranMain,
      DescFirstHeydar: LankaranDesc,
      id: 53,
      special: "Attractive",
      specialization: "Attractive",
      name: "LankaranAquaName",
      openClose: "LankaranAquaOpenClose",
      timeBuild: "LankaranAquaTimeBuild",
      adres: "LankaranAquaAdres",
      cost: "LankaranAquaCost",
      rooms: "LankaranAquaRooms",
      sayt: "LankaranAquaSayt",
      category: "Lənkəran",
      minihistory: "LankaranAquaMinihistory",
      minihistory2: "LankaranAquaMinihistory2",
      titleDescitemTop: "LankaranAquaTitleDescitemTop",
      titleDescitemTopOpis: "LankaranAquaTitleDescitemTopOpis",
      position: [38.762917269887, 48.84791142167508],
    },
    // Nation
    // Nation Qabala
    {
      img: NohurLake,
      descImgMain: NohurLakeMain,
      DescFirstHeydar: NohurLakeDesc,
      id: 54,
      special: "nature",
      specialization: "nature",
      name: "NohurLakeName",
      openClose: "NohurLakeOpenClose",
      timeBuild: "NohurLakeTimeBuild",
      adres: "NohurLakeAdres",
      cost: "NohurLakeCost",
      rooms: "NohurLakeRooms",
      sayt: "NohurLakeSayt",
      category: "Qəbələ",
      minihistory: "NohurLakeMinihistory",
      minihistory2: "NohurLakeMinihistory2",
      titleDescitemTop: "NohurLakeTitleDescitemTop",
      titleDescitemTopOpis: "NohurLakeTitleDescitemTopOpis",
      position: [40.960228854660116, 47.88241978028162],
    },
    // Nation GoyGol
    {
      img: GoyGolLake,
      descImgMain: GoyGolMain,
      DescFirstHeydar: GoyGolDesc,
      id: 55,
      special: "nature",
      specialization: "nature",
      name: "GoyGolLakeName",
      openClose: "GoyGolLakeOpenClose",
      timeBuild: "GoyGolLakeTimeBuild",
      adres: "GoyGolLakeAdres",
      cost: "GoyGolLakeCost",
      rooms: "GoyGolLakeRooms",
      sayt: "GoyGolLakeSayt",
      category: "Gəncə",
      minihistory: "GoyGolLakeMinihistory",
      minihistory2: "GoyGolLakeMinihistory2",
      titleDescitemTop: "GoyGolLakeTitleDescitemTop",
      titleDescitemTopOpis: "GoyGolLakeTitleDescitemTopOpis",
      position: [40.37719373739168, 46.3000380891994],
    },
    // Nature QAX
    {
      img: IlisuVilage,
      descImgMain: IlisuMain,
      DescFirstHeydar: IlisuDesc,
      id: 56,
      special: "nature",
      specialization: "nature",
      name: "IlisuVilageName",
      openClose: "IlisuVilageOpenClose",
      timeBuild: "IlisuVilageTimeBuild",
      adres: "IlisuVilageAdres",
      cost: "IlisuVilageCost",
      rooms: "IlisuVilageRooms",
      sayt: "IlisuVilageSayt",
      category: "Qarışıq yerlər",
      minihistory: "IlisuVilageMinihistory",
      minihistory2: "IlisuVilageMinihistory2",
      titleDescitemTop: "IlisuVilageTitleDescitemTop",
      titleDescitemTopOpis: "IlisuVilageTitleDescitemTopOpis",
      position: [41.468650007305015, 47.057146999383455],
    },
    // Nature Ismayilli
    {
      img: LahicNature,
      descImgMain: LahicMain,
      DescFirstHeydar: LahicDesc,
      id: 57,
      special: "nature",
      specialization: "nature",
      name: "LahijVillageName",
      openClose: "LahijVillageOpenClose",
      timeBuild: "LahijVillageTimeBuild",
      adres: "LahijVillageAdres",
      cost: "LahijVillageCost",
      rooms: "LahijVillageRooms",
      sayt: "LahijVillageSayt",
      category: "Ismayilli",
      minihistory: "LahijVillageMinihistory",
      minihistory2: "LahijVillageMinihistory2",
      titleDescitemTop: "LahijVillageTitleDescitemTop",
      titleDescitemTopOpis: "LahijVillageTitleDescitemTopOpis",
      position: [40.84681636792118, 48.38518377144627],
    },
    // Nature Karabakh
    {
      img: KarabaxNature,
      descImgMain: KarabaxMain,
      DescFirstHeydar: KarabaxDesc,
      id: 58,
      special: "nature",
      specialization: "nature",
      name: "KarabakhMountainsName",
      openClose: "KarabakhMountainsOpenClose",
      timeBuild: "KarabakhMountainsTimeBuild",
      adres: "KarabakhMountainsAdres",
      cost: "KarabakhMountainsCost",
      rooms: "KarabakhMountainsRooms",
      sayt: "KarabakhMountainsSayt",
      category: "Qarabağ",
      minihistory: "KarabakhMountainsMinihistory",
      minihistory2: "KarabakhMountainsMinihistory2",
      titleDescitemTop: "KarabakhMountainsTitleDescitemTop",
      titleDescitemTopOpis: "KarabakhMountainsTitleDescitemTopOpis",
      position: [40.93823065869859, 49.10371939515798],
    },
    {
      img: LankaranNature,
      descImgMain: LankaranGizilMain,
      DescFirstHeydar: LankaranGizilDesc,
      id: 59,
      special: "nature",
      specialization: "nature",
      name: "GizilAghajName",
      openClose: "GizilAghajOpenClose",
      timeBuild: "GizilAghajTimeBuild",
      adres: "GizilAghajAdres",
      cost: "GizilAghajCost",
      rooms: "GizilAghajRooms",
      sayt: "-",
      category: "Lənkəran",
      minihistory: "GizilAghajMinihistory",
      minihistory2: "GizilAghajMinihistory2",
      titleDescitemTop: "GizilAghajTitleDescitemTop",
      titleDescitemTopOpis: "GizilAghajTitleDescitemTopOpis",
      position: [39.170660766035724, 48.9128710925049],
    },
    {
      img: YanardagNature,
      descImgMain: YanardagMainNature,
      DescFirstHeydar: YanardagDescNature,
      id: 60,
      special: "nature",
      specialization: "nature",
      name: "YanarDagName",
      openClose: "YanarDagOpenClose",
      timeBuild: "YanarDagTimeBuild",
      adres: "YanarDagAdres",
      cost: "YanarDagCost",
      rooms: "YanarDagRooms",
      sayt: "YanarDagSayt",
      category: "Bakı",
      minihistory: "YanarDagMinihistory",
      minihistory2: "YanarDagMinihistory2",
      titleDescitemTop: "YanarDagTitleDescitemTop",
      titleDescitemTopOpis: "YanarDagTitleDescitemTopOpis",
      position: [40.502643160522155, 49.89090663408132],
    },
    {
      img: AfrudjaNature,
      descImgMain: AfrudjaMainNature,
      DescFirstHeydar: AfrudjaDescNature,
      id: 61,
      special: "nature",
      specialization: "nature",
      name: "AfurdjaName",
      openClose: "AfurdjaOpenClose",
      timeBuild: "AfurdjaTimeBuild",
      adres: "AfurdjaAdres",
      cost: "AfurdjaCost",
      rooms: "AfurdjaRooms",
      sayt: "AfurdjaSayt",
      category: "Qarışıq yerlər",
      minihistory: "AfurdjaMinihistory",
      minihistory2: "AfurdjaMinihistory2",
      titleDescitemTop: "AfurdjaTitleDescitemTop",
      titleDescitemTopOpis: "AfurdjaTitleDescitemTopOpis",
      position: [41.156666827089175, 48.626316827866056],
    },
    {
      img: QusarSuniNature,
      descImgMain: QusarSuniMain,
      DescFirstHeydar: QusarSuinDesc,
      id: 62,
      special: "nature",
      specialization: "nature",
      name: "susinName",
      openClose: "susinOpenClose",
      timeBuild: "susinTimeBuild",
      adres: "susinAdres",
      cost: "susinCost",
      rooms: "susinRooms",
      sayt: "-",
      category: "Qusar",
      minihistory: "susinMinihistory1",
      minihistory2: "susinMinihistory2",
      titleDescitemTop: "susinTitleTop",
      titleDescitemTopOpis: "susinTitleOpis",
      position: [41.29452908256198, 48.11085440675008],
    },
    //

    //

    // {
    //   id: 119,
    //   name: "Girgir Waterfall",
    //   special: "nature",
    //   specialization: "waterfall",
    //   adres: "Ismayilli, Azerbaijan",
    //   openClose: "Круглосуточно",
    //   timeBuild: "Природное образование",
    //   cost: "Бесплатно",
    //   rooms: "Водопад, леса, горные тропы",
    //   sayt: "-",
    //   category: "Ismayilli",
    //   minihistory:
    //     "Girgir — мощный и красивый водопад в горах Исмаиллы, окружённый густыми лесами и скалами.",
    //   minihistory2:
    //     "Идеальное место для активного отдыха, фотографий и наслаждения природой.",
    // },
    {
      img: BeshbarmagNature,
      descImgMain: BeshbarmagMainNature,
      DescFirstHeydar: BeshbarmagDescNature,
      id: 63,
      special: "nature",
      specialization: "nature",
      name: "beshbarmagName",
      openClose: "beshbarmagOpenClose",
      timeBuild: "beshbarmagTimeBuild",
      adres: "beshbarmagAdres",
      cost: "beshbarmagCost",
      rooms: "beshbarmagRooms",
      category: "Qobustan",
      minihistory: "beshbarmagMiniHistory",
      minihistory2: "beshbarmagMiniHistory2",
      titleDescitemTop: "beshbarmagTitleDescTop",
      titleDescitemTopOpis: "beshbarmagTitleDescTopOpis",
      position: [40.931250224556756, 49.23564277242479],
    },
    {
      img: QusarLazaNature,
      descImgMain: QusarLazaMainNature,
      DescFirstHeydar: QusarLazaDescNature,
      id: 64,
      special: "nature",
      specialization: "nature",
      name: "lazaName",
      openClose: "lazaOpenClose",
      timeBuild: "lazaTimeBuild",
      adres: "lazaAdres",
      cost: "lazaCost",
      rooms: "lazaRooms",
      sayt: "lazaSayt",
      category: "Qusar",
      minihistory: "lazaMiniHistory1",
      minihistory2: "lazaMiniHistory2",
      titleDescitemTop: "lazaTitleTop",
      titleDescitemTopOpis: "lazaTitleOpis",
      position: [41.29322471030304, 48.116545435645456],
    },
    {
      img: MaralgolNature,
      descImgMain: MaralgolMainNature,
      DescFirstHeydar: MaralgolDescNature,
      id: 65,
      special: "nature",
      specialization: "nature",
      name: "maralgolName",
      openClose: "maralgolOpenClose",
      timeBuild: "maralgolTimeBuild",
      adres: "maralgolAdres",
      cost: "maralgolCost",
      rooms: "maralgolRooms",
      sayt: "maralgolSayt",
      category: "Gəncə",
      minihistory: "maralgolMiniHistory1",
      minihistory2: "maralgolMiniHistory2",
      titleDescitemTop: "maralgolTitleTop",
      titleDescitemTopOpis: "maralgolTitleOpis",
      position: [40.37644440769853, 46.312785828832865],
    },
    {
      img: QabalaNature,
      descImgMain: QabalaYeddiMainNature,
      DescFirstHeydar: QabalaYeddiDescNature,
      id: 66,
      special: "nature",
      specialization: "nature",
      name: "yeddigozelName",
      openClose: "yeddigozelOpenClose",
      timeBuild: "yeddigozelTimeBuild",
      adres: "yeddigozelAdres",
      cost: "yeddigozelCost",
      rooms: "yeddigozelRooms",
      sayt: "-",
      category: "Qəbələ",
      minihistory: "yeddigozelMiniHistory1",
      minihistory2: "yeddigozelMiniHistory2",
      titleDescitemTop: "yeddigozelTitleTop",
      titleDescitemTopOpis: "yeddigozelTitleOpis",
      position: [40.9769265788676, 47.91395824901245],
    },
    {
      img: QizilBashNature,
      descImgMain: QizilbashMainNature,
      DescFirstHeydar: QizalbashDescNature,
      id: 67,
      special: "nature",
      specialization: "nature",
      name: "gizilbashName",
      adres: "gizilbashOpenClose",
      openClose: "gizilbashTimeBuild",
      timeBuild: "gizilbashAdres",
      cost: "gizilbashCost",
      rooms: "gizilbashRooms",
      sayt: "-",
      category: "Şamaxı",
      minihistory: "gizilbashMiniHistory1",
      minihistory2: "gizilbashMiniHistory2",
      titleDescitemTop: "gizilbashTitleTop",
      titleDescitemTopOpis: "gizilbashTitleOpis",
      position: [40.64474701428576, 48.67181281267531],
    },

    {
      img: TangiyatiNature,
      descImgMain: TangiyatiMainNature,
      DescFirstHeydar: TangiyatiDescNature,
      id: 68,
      special: "nature",
      specialization: "nature",
      name: "tengyaltiName",
      adres: "tengyaltiAdres",
      openClose: "tengyaltiOpenClose",
      timeBuild: "tengyaltiTimeBuild",
      cost: "tengyaltiCost",
      rooms: "tengyaltiRooms",
      sayt: "-",
      category: "Qarışıq yerlər",
      minihistory: "tengyaltiMiniHistory1",
      minihistory2: "tengyaltiMiniHistory2",
      titleDescitemTop: "tengyaltiTitleTop",
      titleDescitemTopOpis: "tengyaltiTitleOpis",
      position: [41.290574016422866, 48.071833721743076],
    },

    //    {
    //   id: 124,
    //   name: "Girgir Mountain",
    //   special: "nature",
    //   specialization: "mountain",
    //   adres: "Ismayilli, Azerbaijan",
    //   openClose: "Круглосуточно",
    //   timeBuild: "Древние горы",
    //   cost: "Бесплатно",
    //   rooms: "Горные тропы, леса, виды",
    //   sayt: "-",
    //   category: "Ismayilli",
    //   minihistory:
    //     "Гора Girgir — часть Кавказского хребта, покрыта хвойными лесами, популярна среди туристов и альпинистов.",
    //   minihistory2:
    //     "Предлагает отличные маршруты для треккинга и живописные панорамные виды на окрестности.",
    // }, \\qazwz\qawqa\zw\wzqw

    // Park
    {
      img: HighPark,
      descImgMain: HighParkMain,
      DescFirstHeydar: HighParkFunikler,
      DescSecondImg: HighParkFunikler,
      id: 69,
      special: "Attractive",
      specialization: "Attractive",
      name: "Highland Park",
      openClose: "Круглосуточна",
      timeBuild: "построен с 1935 г., реконструирован в 2011–2013 гг.",
      adres: "Highland Park/Alley of Martyrs",
      cost: "1 AZN",
      rooms: "Количество выставочных залов: 5",
      sayt: "-",
      category: "Bakı",
      minihistory:
        "Вот подробный обзор Highland Park (Нагорный парк / Dağüstü Park) и смотровой площадки — одного из самых впечатляющих и значимых мест в Баку:",
      minihistory2:
        "Он предлагает изумительные панорамные виды на Каспийское море, Пламенные башни, набережную Баку, Старый город (Ичери‑Шехер), дворец Ширваншахов и бухту",
      titleDescitemTop: "Нагорный парк — сердце Баку с видом в вечность",
      titleDescitemTopOpis:
        "Высоко над шумными улицами, где город сменяет суету на тишину, раскинулся Нагорный парк — живописное и символичное место, где история, природа и архитектура переплетаются в одной гармонии. Здесь дыхание Баку становится особенно лёгким, а взгляд — особенно дальним. Это не просто парк. Это — вид на душу города.Прогуливаясь по тенистым аллеям Нагорного парка, ты словно попадаешь в другой Баку — спокойный, созерцательный, наполненный светом и смыслом. Здесь растут стройные кипарисы, пальмы и ухоженные клумбы, поют птицы, шепчет ветер… . С каждым шагом ты поднимаешься выше — к самой вершине города, где тебя встречают лучшие панорамы столицы: сверкающий Каспий, Приморский бульвар, Пламенные башни, Старый город и бескрайнее небо.",
      titleDescitemBottom: "Бакинский фуникулёр — путь в небо над городом",
      titleDescitembottomOpis:
        "Представь: шумный Баку остаётся внизу, а ты плавно поднимаешься всё выше и выше, будто скользишь по невидимой нити в небеса. Перед тобой открываются завораживающие панорамы города, Каспий переливается золотом заката, а сердце замирает от красоты. Всё это — Бакинский фуникулёр, единственный в своём роде в Азербайджане и настоящий символ романтики, ностальгии и духа времени. Бакинский фуникулёр был открыт ещё в 1960 году и стал первым в Закавказье. С тех пор он не раз модернизировался, но сохранил свою душу — тот самый неспешный ритм, мягкое движение и завораживающее ощущение перехода из повседневности в волшебство. Во время подъёма кажется, что ты перемещаешься сквозь времена — от исторических улиц центра до мемориальной Аллеи Шехидов, туда, где воздух чище, а мысли светлее.",
    },
    {
      img: GoyGolLake,
      descImgMain: GoyGolMain,
      DescFirstHeydar: GoyGolDesc,
      id: 70,
      special: "Парки",
      specialization: "Парки",
      name: "Göygöl National Park (Göygöl Milli Parkı)",
      openClose: "Ежедневно: 09:00–18:00",
      timeBuild: "Основан в 2008 году",
      adres: "Gəncə yaxınlığında, Азербайджан",
      cost: "Вход: 2 AZN для взрослых, 1 AZN для детей",
      rooms: "Тропы для прогулок, смотровые площадки, зоны для пикника",
      sayt: "-",
      category: "Gəncə",
      minihistory:
        "Göygöl — горное озеро с кристально чистой водой, образованное в результате землетрясения в XVIII веке.",
      minihistory2:
        "Вода настолько прозрачная, что отражает весь горный пейзаж, а вокруг проложены тропы для прогулок.",
      titleDescitemTop: "Göygöl — жемчужина Кавказских гор",
      titleDescitemTopOpis:
        "Göygöl — это чистейшее озеро в национальном парке с хвойными лесами и живописными тропами. Идеальное место для пеших прогулок, фотосессий и отдыха на природе.GöyGöygöl — это чистейшее озеро в национальном парке с хвойными лесами и живописными тропами. Идеальное место для пеших прогулок, фотосессий и отдыха на природе.göl — это чистейшее озеро в национальном парке с хвойными лесами и живописными тропами. ИдеальноеGöygöl — это чистейшее озеро в национальном парке с хвойными лесами и живописными тропами. Идеальное место для пеших прогулок, фотосессий и отдыха на природе. место для пеших прогулок, фотосессий и отдыха на природе.",
    },
    {
      img: ShamaxiMedrese,
      descImgMain: ShamaxiMedreseMain,
      DescFirstHeydar: ShamaxiMedreseDesc2,
      id: 71,
      special: "palaces",
      specialization: "Дворцы",
      name: "shamakhiMosqueName",
      openClose: "shamakhiMosqueOpenClose",
      timeBuild: "shamakhiMosqueTimeBuild",
      adres: "shamakhiMosqueAdres",
      cost: "shamakhiMosqueCost",
      rooms: "shamakhiMosqueRooms",
      sayt: "-",
      category: "Şamaxı",
      minihistory: "shamakhiMosqueMinihistory",
      minihistory2: "shamakhiMosqueMinihistory2",
      titleDescitemTop: "shamakhiMosqueTitleDescitemTop",
      titleDescitemTopOpis: "shamakhiMosqueTitleDescitemTopOpis",
      position: [40.62705871299343, 48.6438404394922],
    },
    {
      img: Diribaba,
      descImgMain: DiriBabaMain,
      DescFirstHeydar: DiriBabaDesc,
      id: 72,
      special: "palaces",
      specialization: "Дворцы",
      name: "diriBabaName",
      openClose: "diriBabaOpenClose",
      timeBuild: "diriBabaTimeBuild",
      adres: "diriBabaAdres",
      cost: "diriBabaCost",
      rooms: "diriBabaRooms",
      sayt: "-",
      category: "Qobustan",
      minihistory: "diriBabaMinihistory",
      minihistory2: "diriBabaMinihistory2",
      titleDescitemTop: "diriBabaTitleDescTop",
      titleDescitemTopOpis: "diriBabaTitleDescOpis",
    },
    {
      img: QobustanQorgu,
      descImgMain: QobustanQorguMain,
      DescFirstHeydar: QobustanQorguDesc,
      id: 73,
      special: "palaces",
      specialization: "Дворцы",
      name: "qobustanName",
      openClose: "qobustanOpenClose",
      timeBuild: "qobustanTimeBuild",
      adres: "qobustanAdres",
      cost: "qobustanCost",
      rooms: "qobustanRooms",
      sayt: "http://gobustan-rockart.az",
      category: "Qobustan",
      minihistory: "qobustanMinihistory",
      minihistory2: "qobustanMinihistory2",
      titleDescitemTop: "qobustanTitleDescTop",
      titleDescitemTopOpis: "qobustanTitleDescOpis",
    },
    {
      img: QobustanVolcano,
      descImgMain: QobustanVolcanoMain,
      DescFirstHeydar: QobustanVolcanoDesc,
      id: 74,
      special: "nature",
      specialization: "Природный объект",
      name: "QobustanVolcanoName",
      openClose: "QobustanVolcanoOpenClose",
      timeBuild: "QobustanVolcanoTimeBuild",
      adres: "QobustanVolcanoAdres",
      cost: "QobustanVolcanoCost",
      rooms: "QobustanVolcanoRooms",
      sayt: "https://azerbaijan.travel/mud-volcanoes",
      category: "Qobustan",
      minihistory: "QobustanVolcanoMiniHistory1",
      minihistory2: "QobustanVolcanoMiniHistory2",
      titleDescitemTop: "QobustanVolcanoTitle",
      titleDescitemTopOpis: "QobustanVolcanoOpis",
    },
    {
      img: ShekiWall,
      descImgMain: ShekiWallMain,
      DescFirstHeydar: ShekiWallDesc,
      id: 75,
      special: "palaces",
      specialization: "Дворцы",
      name: "ShekiFortressName",
      openClose: "ShekiFortressOpenClose",
      timeBuild: "ShekiFortressTimeBuild",
      adres: "ShekiFortressAdres",
      cost: "ShekiFortressCost",
      rooms: "ShekiFortressRooms",
      sayt: "-",
      category: "Şəki",
      minihistory: "ShekiFortressMiniHistory1",
      minihistory2: "ShekiFortressMiniHistory2",
      titleDescitemTop: "ShekiFortressTitleDesc",
      titleDescitemTopOpis: "ShekiFortressTitleDescOpis",
    },
    {
      img: SekiAlbani,
      descImgMain: SekiAlbaniMain,
      DescFirstHeydar: SekiAlbaniDesc,
      id: 76,
      special: "palaces",
      specialization: "Дворцы",
      name: "KishTempleName",
      openClose: "KishTempleOpenClose",
      timeBuild: "KishTempleTimeBuild",
      adres: "KishTempleAdres",
      cost: "KishTempleCost",
      rooms: "KishTempleRooms",
      sayt: "-",
      category: "Şəki",
      minihistory: "KishTempleMiniHistory1",
      minihistory2: "KishTempleMiniHistory2",
      titleDescitemTop: "KishTempleTitleDesc",
      titleDescitemTopOpis: "KishTempleTitleDescOpis",
    },
    {
      img: SekiXanMosque,
      descImgMain: SekiXanMosqueMain,
      DescFirstHeydar: SekiXanMosqueDesc,
      id: 77,
      special: "palaces",
      specialization: "Дворцы",
      name: "ShekiKhanMosqueName",
      openClose: "ShekiKhanMosqueOpenClose",
      timeBuild: "ShekiKhanMosqueTimeBuild",
      adres: "ShekiKhanMosqueAdres",
      cost: "ShekiKhanMosqueCost",
      rooms: "ShekiKhanMosqueRooms",
      sayt: "-",
      category: "Şəki",
      minihistory: "ShekiKhanMosqueMiniHistory1",
      minihistory2: "ShekiKhanMosqueMiniHistory2",
      titleDescitemTop: "ShekiKhanMosqueTitleDesc",
      titleDescitemTopOpis: "ShekiKhanMosqueTitleDescOpis",
    },
  ];

  const [season, setSeason] = useState([]);

  const addToDesc = (product) => {
    setSeason([{ ...product, postId: 1 }]);
  };

  const SeasonData = [
    {
      id: 1,
      img: GS,
      postId: 1,
      name: "Габала",
      title: "Чeм интересен путешествие в Габалу",
    },
    { id: 2, img: NS, postId: 1, name: "Набран" },
    { id: 3, img: SHS, postId: 1, name: "Шеки" },
    { id: 4, img: SHW, postId: 3, name: "Шахдаг" },
    { id: 5, img: TufWin, postId: 3, name: "Туфандаг" },
    { id: 6, img: HinWin, postId: 3, name: "Хыналыг" },
    { id: 7, img: SS, postId: 2, name: "Шеки" },
    { id: 8, img: SG, postId: 2, name: "Гах" },
    { id: 9, img: Ls, postId: 2, name: "Лерик" },
  ];

  const [language, setLanguage] = useState("az");
  const handleLanguageChange = (event) => {
    setLanguage(event.target.value);
  };

  return (
    <MyContext.Provider
      value={{
        handleLanguageChange,
        language,
        translations,
        punktMenu,
        museums,
        traveled,
        SeasonData,
        addToDesc,
        season,
      }}
    >
      {children}
    </MyContext.Provider>
  );
};

export const useMyContext = () => {
  const context = useContext(MyContext);
  if (!context) {
    throw new Error("useMyContext должен использоваться внутри MyProvider");
  }
  return context;
};

//
