import { createContext, useContext, useState, useEffect } from "react";

import HeydarAliyevCenter from "./assets/images/HeydarAliyevCenter.png";
import CarpetMuseumBaku from "./assets/images/Carpet.png";
import ArtMuseum from "./assets/images/ArtMuseum.png";
import MiniBook from "./assets/images/MiniBook.png";
import FireXram from "./assets/images/FireXram.png";
import NationalMusey from "./assets/images/NationalMusey.png";
import Literaturi from "./assets/images/LiteraturiMuseum.png";
import CentralMusei from "./assets/images/CentralMusei.png";
import IsteglalMusei from "./assets/images/IsteglalMusei.png";
import VurgunOlace from "./assets/images/Vurgunhouse.png";
import UzeirHouse from "./assets/images/UzeirHouse.png";
import JafarJabbarliHousem from "./assets/images/jafarjabbarlihousem.png";
import GanjaHistory from "./assets/images/GanjaHistory.png";
import MuzeyGandjs from "./assets/images/MuzeyGandjs.png";
import ShekiMuzet from "./assets/images/ShekiMuzey.png";
import ShekiMuzeyKravoed from "./assets/images/ShekiMuzeyKravoed.png";
import LankoranMuzey from "./assets/images/LankoranMuzey.png";
import LankoranHaziMuzey from "./assets/images/LankoranHaziHouseMuzey.png";
import ShamaxiMuzey from "./assets/images/ShamaxiMuzey.png";
import CarpetShusaMuzey from "./assets/images/CarpetShusaMuzey.png";
import MavzouleyShusa from "./assets/images/MouvsoleyShusha.png";
import BulBulMuzeyShusha from "./assets/images/BulBulMuzeyShusha.png";
import GabalaGeologCenter from "./assets/images/GabalaGeologCenter.png";
import GabalaKraevodMuzey from "./assets/images/GabalaKraevodMuzey.png";
import XacmazMuzeum from "./assets/images/XacmazMuzeum.png";
import MuzeumXacmaxfreinds from "./assets/images/MuzeumFreinds.png";
import XacmazCarpetMuzeum from "./assets/images/MuzeyCarpetXacmaz.png";
import ShamkirFlagsMuzey from "./assets/images/ShamkirFlagsMuzey.png";
import LahicKraevodMuzey from "./assets/images/LahicKraevodMuzey.png";
import YaratMusey from "./assets/images/YaratMuseum.png";

import HighPark from "./assets/images/BakuHigh.png";

// Atraction import

import SeeBreez from "./assets/images/SeeBreezActraction.png";
import SkyPark from "./assets/images/SkyParkActraction.png";
import VrPark from "./assets/images/VrParkAttractive.png";
import ShootingPark from "./assets/images/ShootingAttractive.png";
import Shagdag from "./assets/images/ShagdagAttractive.png";
import Safari from "./assets/images/SafariAttractive.png";
import HorseClub from "./assets/images/HorseClub.png";
import Gabalalnd from "./assets/images/QabalalandAtraction.png";
import Karting from "./assets/images/KartingBakuAttraction.png";
import Waterpark from "./assets/images/WaterparkAttraction.png";
import GanjaPaintBall from "./assets/images/GanjaPaintBallAtraction.png";
import GoyGolOffRoad from "./assets/images/GoyGolOffRoadAttraction.png";
import ZireZig from "./assets/images/ZireZipAttraction.png";
import GabalaShooting from "./assets/images/GabalaShootingAttraction.png";
import BakuClimbingGym from "./assets/images/ClimbingBakuAttraction.png";
import AquaParkNovyyLankaran from "./assets/images/LankaranAguaAtrraction.png";
import BakuEye from "./assets/images/BakuEyeAttraction.png";
import DalgaBeach from "./assets/images/DalgaBeachAttraction.png";
import Bowling from "./assets/images/BowlingAttraction.png";

import DescImg from "./assets/images/FCenter.png";
import DescFirstHeydar from "./assets/images/DescFirstHeydar.png";
import MiniAzer from "./assets/images/MiniAzer.png";
import MuzeyCaroet from "./assets/images/MuzeyCarpetdesc.png";
import MiniCarpet from "./assets/images/MiniCarpetDesc.png";
import MiniCarpet2 from "./assets/images/MiniCarpetDesc2.png";
import MuzeyArtMain from "./assets/images/MuzeyArtDesc.png";
import MuzeyArtMainItem from "./assets/images/MuzeyArtDescMainItem.png";
import MiniBookArtMain from "./assets/images/MiniBookMainDesc.png";
import MiniBookArtMainItem from "./assets/images/MiniBookArtMainItem.png";
import MiniBookArtMainItem2 from "./assets/images/MiniBookArtMainItem2.png";
import YaratMain from "./assets/images/YaratMain.png";
import YaratDesc from "./assets/images/YarartDesc.png";
import AteshgaxMain from "./assets/images/AteshgaxMain.png";
import AteshgaxDesc from "./assets/images/AteshgaxDescOpis.png";
import AteshgaxDesc2 from "./assets/images/AteshgaxDescOpis2.png";
import NationalMuseyMain from "./assets/images/NationalMuseyMain.png";
import NationalMuseyInside from "./assets/images/NationalMuseyDesc.png";
import NationalMuseyExtra from "./assets/images/NationalMuseyDesc2.png";
import LiteraturiMain from "./assets/images/MuseyNationalLiteraturiMain.png";
import LiteraturiInside from "./assets/images/MuseyNationalLiteraturidesc.png";
import LiteraturiExtra from "./assets/images/MuseyNationalLiteraturidesc2.png";
import CentralMuseiMain from "./assets/images/MuseumcenterMain.png";
import CentralMuseiInside from "./assets/images/MuseumcenterDesc.png";
import IsteglalMuseiMain from "./assets/images/IsteglalMuseiMain.png";
import IsteglalMuseiInside from "./assets/images/IsteglalMuseidesc.png";
import VurgunOlaceMain from "./assets/images/VurgunPLaceMain.png";
import VurgunOlaceInside from "./assets/images/VurgunPLaceDesc.png";
import HouseUzeirMuseumMain from "./assets/images/HouseUzeirMuseumDesc.png";
import HouseUzeirMuseumDesc from "./assets/images/HouseUzeirMuseumMain.png";
import HouseJafarbliMuseumMain from "./assets/images/jafarjabbarlihousemMain.png";
import HouseJafarbliMuseumDesc from "./assets/images/jafarjabbarlihousemdesc.png";
import GanjaHistoryMain from "./assets/images/GanjaHistoryMain.png";
import GanjaHistoryDesc from "./assets/images/GanjaHistoryDesc.png";
import GanjaMuseumMain from "./assets/images/MuzeyGandjsMain.png";
import GanjaMuseumDesc from "./assets/images/MuzeyGandjsDesc.png";
import ShamaxiMedrese from "./assets/images/ShamaxiCumaMedrese.png";
import ShamaxiMedreseMain from "./assets/images/ShamaxiCumaMedreseMain.png";
import ShamaxiMedreseDesc2 from "./assets/images/ShamaxiCumaMedreseDesc2.png";
import Diribaba from "./assets/images/DiriBabaNaxcivan.png";
import DiriBabaMain from "./assets/images/DiriBabaNaxcivanMain.png";
import DiriBabaDesc from "./assets/images/DiriBabaNaxcivanDesc.png";
import QobustanQorgu from "./assets/images/QobustanQorquMuzey.png";
import QobustanQorguMain from "./assets/images/QobustanQorquMuzeyMain.png";
import QobustanQorguDesc from "./assets/images/QobustanQorquMuzeyDesc.png";
import QobustanVolcano from "./assets/images/QobustanVulkan.png";
import QobustanVolcanoMain from "./assets/images/QobustanVulkanMain.png";
import QobustanVolcanoDesc from "./assets/images/QobustanVulkanDesc.png";
import ShekiWall from "./assets/images/ShekiDostopremecatelnost.png";
import ShekiWallMain from "./assets/images/ShekiDostopremecatelnostMain.png";
import ShekiWallDesc from "./assets/images/ShekiDostopremecatelnostDesc.png";
import SekiAlbani from "./assets/images/SekiAlbani.png";
import SekiAlbaniMain from "./assets/images/SekiAlbaniMain.png";
import SekiAlbaniDesc from "./assets/images/SekiAlbaniDesc.png";
import SekiXanMosque from "./assets/images/SekiXan.png";
import SekiXanMosqueMain from "./assets/images/SekiXanMain.png";
import SekiXanMosqueDesc from "./assets/images/SekiXanDesc.png";
import ShekiMehemmed from "./assets/images/SheyxMehemedMosgou.png";
import ShekiMehemmedMain from "./assets/images/SheyxMehemedMosgouMain.png";
import ShekiMehemmedDesc from "./assets/images/SheyxMehemedMosgoudesc.png";
import AsmaKorpusu from "./assets/images/AsmaKorpusu.png";
import AsmaKorpusuMain from "./assets/images/AsmaKorpusuMain.png";
import AsmaKorpusuDesc from "./assets/images/AsmaKorpusuDesc.png";
import LakeSide from "./assets/images/LakeSide.png";
import LakeSideMain from "./assets/images/LakeSideMain.png";
import LakeSideDesc from "./assets/images/LakeSideDesc.png";
import Xanqizi from "./assets/images/XanQizidesc.png";
import XanqiziMain from "./assets/images/XanQiziMain.png";
import XanqiziDesc from "./assets/images/XanQizi.png";
import SushaQala from "./assets/images/SushaQala.png";
import SushaQalaMain from "./assets/images/SushaQalaMain.png";
import SushaQalaDesc from "./assets/images/SushaQalaDesc.png";
import AlmanCirch from "./assets/images/AlmanCercie.png";
import AlmanCirchMain from "./assets/images/AlmanCercieMain.png";
import AlmanCirchDesc from "./assets/images/AlmanCercieDesc.png";
import YeddiQunbez from "./assets/images/YeddiQuzelSamaxi.png";
import YeddiQunbezMain from "./assets/images/YeddiQuzelSamaxiMain.png";
import YeddiQunbezDesc from "./assets/images/YeddiQuzelSamaxiDesc.png";
import Pirqulu from "./assets/images/PirquluShamaxim.png";
import PirquluMain from "./assets/images/PirquluShamaxi.png";
import PirquliDesc from "./assets/images/pirquluShamaxidesc.png";
import ShamkirCastle from "./assets/images/ShamkirQala.png";
import ShamkirCastleMain from "./assets/images/ShamkirQalaMain.png";
import ShamkirCastleDesc from "./assets/images/ShamkirQalaDesc.png";
import ShamkirMuzey from "./assets/images/ShamkirMuseymHistory.png";
import ShamkirMuzeyMain from "./assets/images/ShamkirMuseymHistoryMain.png";
import ShamkirMuzeyDesc from "./assets/images/ShamkirMuseymHistoryMainDesc.png";
import ShekiSareyMain from "./assets/images/ShekiSarayMain.png";
import ShekiSareyDesc from "./assets/images/ShekiSarayMain.png";
import ShekiTarixMain from "./assets/images/ShekiTarixMain.png";
import ShekiTarixDesc from "./assets/images/ShekiTarixDesc.png";
import LankaranMuseyMain from "./assets/images/LankaranMuzeyMain.png";
import LankaranMuseyDesc from "./assets/images/LankaranMuzeyDesc.png";
import LankaranEzizMain from "./assets/images/LankaranEzizMain.png";
import LankaranEzizDesc from "./assets/images/LankaranEzizDesc.png";
import ShamaxiResedxanasiMain from "./assets/images/ShamaxiResedxanasiMain.png";
import ShamaxiResedxanasiDesc from "./assets/images/ShamaxiResedxanasiDesc.png";
import ShushaCarpetMuzeyMain from "./assets/images/ShushaCarpetMuzeyDesc.png";
import ShushaCarpetMuzeyDesc from "./assets/images/SushaCarpetMuzeyMain.png";
import ShushaVagifMuzeyMain from "./assets/images/ShushaVagifMuzeyMain.png";
import ShushaVagifMuzeyDescs from "./assets/images/SushaVagifDesc.png";
import BulBulMuzeyShushaMain from "./assets/images/BulBulMuzeyShushaMain.png";
import BulBulMuzeyShushaDesc from "./assets/images/BulBulMuzeyShushaDesc.png";
import GabalaGeologCenterMain from "./assets/images/QabalaArxeolojiMerkeziMain.png";
import GabalaGeologCenterDesc from "./assets/images/QabalaArxeolojiMerkeziDesc.png";
import GabalaKraevodMuzeyMain from "./assets/images/GabalaKraevodMuzeyMain.png";
import GabalaKraevodMuzeyDesc from "./assets/images/GabalaKraevodMuzeyDesc.png";
import XacmazMuzeumMain from "./assets/images/XacmazMuzeumMain.png";
import XacmazMuzeumDesc from "./assets/images/XacmazMuzeumDesc.png";
import XacmazMuzeumFreindsDesc from "./assets/images/MuzeyXacmazDesc.png";
import XacmazCarpetMain from "./assets/images/XacmazCarpetMain.png";
import XacmazCarpetDesc from "./assets/images/XacmazCarpetDesc.png";

// NATURE

import NohurLake from "./assets/images/NohurLakeNature.png";
import GoyGolLake from "./assets/images/GoyGolNature.png";
import IlisuVilage from "./assets/images/IlisuNature.png";
import LahicNature from "./assets/images/LahicNature.png";
import KarabaxNature from "./assets/images/KarabaxNation.png";
import LankaranNature from "./assets/images/LankaranGizilNature.png";
import YanardagNature from "./assets/images/YanardagNature.png";
import AfrudjaNature from "./assets/images/AfrudjaNature.png";
import QusarSuniNature from "./assets/images/QusarSuniNature.png";
import BeshbarmagNature from "./assets/images/BeshmarmagNature.png";
import QusarLazaNature from "./assets/images/QusarLazaNature.png";
import MaralgolNature from "./assets/images/MaralgolNature.png";
import QabalaNature from "./assets/images/QabalaYeddiNaature.png";
import QizilBashNature from "./assets/images/QizilbashNature.png";
import TangiyatiNature from "./assets/images/TanyagatiNature.png";

import NohurLakeMain from "./assets/images/NohurLakeMain.png";
import NohurLakeDesc from "./assets/images/NohurLakeDesc.png";
import GoyGolMain from "./assets/images/GoygolMain.png";
import GoyGolDesc from "./assets/images/GoygolDesc.png";
import IlisuMain from "./assets/images/IlisuMain.png";
import IlisuDesc from "./assets/images/IlisuDesc.png";
import LahicMain from "./assets/images/LahicMainNature.png";
import LahicDesc from "./assets/images/LahicDescNAature.png";
import KarabaxMain from "./assets/images/KarabaxMainNature.png";
import KarabaxDesc from "./assets/images/KarabaxDescNature.png";
import LankaranGizilMain from "./assets/images/LankaranGizilMain.png";
import LankaranGizilDesc from "./assets/images/LankaranGizilDesc.png";
import YanardagMainNature from "./assets/images/YanardagMainNature.png";
import YanardagDescNature from "./assets/images/YanarDagDescNature.png";
import AfrudjaMainNature from "./assets/images/AfrudjaMainNature.png";
import AfrudjaDescNature from "./assets/images/AfrudjaDescNature.png";
import QusarSuniMain from "./assets/images/QusarSuniMain.png";
import QusarSuinDesc from "./assets/images/QusarSuniDesc.png";
import BeshbarmagMainNature from "./assets/images/BeshmarmagNatureMain.png";
import BeshbarmagDescNature from "./assets/images/BeshmarmagDescNature.png";
import QusarLazaMainNature from "./assets/images/QusarLazaMainNAture.png";
import QusarLazaDescNature from "./assets/images/QusarLazaDescNature.png";
import MaralgolMainNature from "./assets/images/MaralgolMainNature.png";
import MaralgolDescNature from "./assets/images/MaralgolDescNature.png";
import QabalaYeddiMainNature from "./assets/images/QabalaYeddiMainNature.png";
import QabalaYeddiDescNature from "./assets/images/QabalaYeddiDescNature.png";
import QizilbashMainNature from "./assets/images/QizilbashMainNature.png";
import QizalbashDescNature from "./assets/images/QizilbashDescNature.png";
import TangiyatiMainNature from "./assets/images/TanyagatiMainNature.png";
import TangiyatiDescNature from "./assets/images/TanyagatiDescNature.png";

import HighParkMain from "./assets/images/HighParkMain.png";
import HighParkFunikler from "./assets/images/HighParkFunickler.png";
import SeeBreezMain from "./assets/images/SeeBreezMain.png";
import SeeBreezF from "./assets/images/SeeBreezF.png";
import SkyParkMain from "./assets/images/SkyParkMain.png";
import SkyParkZone from "./assets/images/SkyZone.png";
import VrParkMain from "./assets/images/VrParkMain.png";
import VrParkDesc from "./assets/images/VrParkDesc.png";
import ShootingMain from "./assets/images/ShootingMain.png";
import ShootingMainDesc from "./assets/images/ShootingMainDesc.png";
import ShootingMainDesc2 from "./assets/images/ShootingMainDesc2.png";
import ShagdagMain from "./assets/images/ShagdagMain.png";
import ShagdagMainDesc from "./assets/images/ShagdagMainDesc.png";
import ShagdagMainDesc2 from "./assets/images/ShagdagMainDesc2.png";
import SafariMain from "./assets/images/SafariMain.png";
import SafariMainDesc from "./assets/images/SafariMainDesc.png";
import SafariMainDesc2 from "./assets/images/SafariMainDesc2.png";
import HorseClubMain from "./assets/images/HorseClubMain.png";
import HorseClubDesc1 from "./assets/images/HorseClubDesc1.png";
import GabalalanfMain from "./assets/images/QabalalandMain.png";
import GabalalanfDesc from "./assets/images/QabalandDesc.png";
import KartingMain from "./assets/images/KartingMain.png";
import KartingDesc1 from "./assets/images/KartingDesc.png";
import WaterparkMain from "./assets/images/WaterparkMain.png";
import WaterparkDesc1 from "./assets/images/WaterparkDesc1.png";
import GanjaPaintMain from "./assets/images/GanjaPaintBallMain.png";
import GanjaPaintDesc from "./assets/images/GanjaPaintBallDesc.png";
import GoyGolOffRoadMain from "./assets/images/GoyGolOffRoadMain.png";
import GoyGolOffRoadDesc from "./assets/images/GoyGolOffRoadDesc.png";
import ZireZigMain from "./assets/images/ZireZipMain.png";
import ZireZigDesc from "./assets/images/ZireZipDesc.png";
import GabalaShootingMain from "./assets/images/GabalaShootingMain.png";
import GabalaShootingDesc from "./assets/images/GabalaShootingdesc.png";
import BakuClimbingGymMain from "./assets/images/BakuClimbingMain.png";
import BakuClimbingGymDesc from "./assets/images/BakuClimbingDesc.png";
import LankaranMain from "./assets/images/LankaranAguaMain.png";
import LankaranDesc from "./assets/images/LankaranAguaDesc.png";
import BakuEyeMain from "./assets/images/BakuEyeMain.png";
import BakuEyeDesc from "./assets/images/BakuEyeDesc.png";
import DalgaBeachMain from "./assets/images/DalgaBeachMain.png";
import DalgaBeachDesc from "./assets/images/DalgaBeachDesc.png";
import BowlingMain from "./assets/images/BowlingMain.png";
import BowlingDesc from "./assets/images/BowlingDesc.png";
import ZooPark from "./assets/images/ZooParkBakumain.png";
import ZooParkMain from "./assets/images/ZooParkBaku.png";
import ZooParkDesc from "./assets/images/ZooParkBakuDesc.png";
import TofigStadion from "./assets/images/TofigStadion.png";
import TofigStadionMain from "./assets/images/TofigStadionMain.png";
import TofigStadionDesc from "./assets/images/TofigStadionDesc.png";
import OlympicStadion from "./assets/images/Olimpikstadion.png";
import OlympicStadionMain from "./assets/images/OlimpikstadionMain.png";
import OlympicStadionDesc from "./assets/images/OlimpikstadionDesc.png";
import HeydarAliyevArenaStadion from "./assets/images/HeydarAliyevStadion.png";
import HeydarAliyevArenaStadionMain from "./assets/images/HeydarAliyevCenterMain.png";
import HeydarAliyevArenaStadionDesc from "./assets/images/HeydarAliyevStadionDesc.png";
import BakuCrystalHall from "./assets/images/BakuCrystalHall.png";
import BakuCrystalHallMain from "./assets/images/BakuCrystalHallMain.png";
import BakuCrystalHallDesc from "./assets/images/BakuCrystalHallDsc.png";
import BakuSportsHall from "./assets/images/BakuSportsHall.png";
import BakuSportsHallMain from "./assets/images/BakuSportsHallMain.png";
import BakuSportsHallDesc from "./assets/images/BakuSportsHallDesc.png";
import QizQalasi from "./assets/images/QizQalasi.png";
import QizQalasiMain from "./assets/images/QizQalasiMain.png";
import QizQalasiDesc from "./assets/images/QizQalasiDesc.png";
import BakuYachtClub from "./assets/images/ShipClubBaku.png";
import BakuYachtClubMain from "./assets/images/ShipClubBakuMain.png";
import BakuYachtClubDesc from "./assets/images/ShipClubBakuMainDesc.png";
import PhilharmonicGarden from "./assets/images/FelormoniyaBaku.png";
import PhilharmonicGardenMain from "./assets/images/FelormoniyaBakuMain.png";
import PhilharmonicGardenDesc from "./assets/images/FelormoniyaBakuDesc.png";
import FlameTowers from "./assets/images/FlameTower.png";
import FlameTowersMain from "./assets/images/FlameTowerMain.png";
import FlameTowersDesc from "./assets/images/FlameTowerDesc.png";
import GulustanPalace from "./assets/images/GulustanPalaces.png";
import GulustanPalaceMain from "./assets/images/GulustanPalacesMain.png";
import GulustanPalaceDesc from "./assets/images/GulustanPalacesDesc.png";
import LittleVenice from "./assets/images/LittleVenice.png";
import LittleVeniceMain from "./assets/images/LittleVeniceMain.png";
import LittleVeniceDesc from "./assets/images/LittleVeniceDesc.png";
import WarTrophiesPark from "./assets/images/WarTrophiesPark.png";
import WarTrophiesParkMain from "./assets/images/WarTrophiesParkMain.png";
import WarTrophiesParkDesc from "./assets/images/WarTrophiesParkDesc.png";

import GS from "./ServicesProvidedComponent/asestss/GabalaSeason.png";
import NS from "./ServicesProvidedComponent/asestss/NabranSeason.png";
import SHS from "./ServicesProvidedComponent/asestss/ShekiSeason.png";

import SHW from "./ServicesProvidedComponent/asestss/SahdagWinter.png";
import TufWin from "./ServicesProvidedComponent/asestss/TufanWinter.png";
import HinWin from "./ServicesProvidedComponent/asestss/HinaligWinter.png";

import SS from "./ServicesProvidedComponent/asestss/ShekiSpring.png";
import SG from "./ServicesProvidedComponent/asestss/SpringGax.png";
import Ls from "./ServicesProvidedComponent/asestss/LerikSpring.png";

const MyContext = createContext();

export const MyProvider = ({ children }) => {
  const translations = {};

  const [punktMenu, setPunktMenu] = useState([]);

  const [point, setPointed] = useState();

  const [museums, setMuseums] = useState([]);

  const traveled = [
    {
      img: HeydarAliyevCenter,
      descImgMain: DescImg,
      DescFirstHeydar: DescFirstHeydar,
      DescSecondImg: MiniAzer,
      id: 1,
      name: "heydarAliyevCultureCenter",
      openClose: "openCloseHeydarAliyev",
      timeBuild: "timeBuildHeydarAliyev",
      adres: "adresHeydarAliyev",
      rooms: "roomsHeydarAliyev",
      sayt: "saytHeydarAliyev",
      category: "Bakı",
      city: "baku",
      special: "museums",
      specialTranslate: "museums",
      specialization: "Музей",
      minihistory: "minihistoryHeydarAliyev",
      minihistory2: "minihistory2HeydarAliyev",
      titleDescitemTop: "titleDescitemTopHeydarAliyev",
      titleDescitemTopOpis: "titleDescitemTopOpisHeydarAliyev",
      titleDescitemBottom: "titleDescitemBottomHeydarAliyev",
      titleDescitembottomOpis: "titleDescitemBottomOpisHeydarAliyev",
      position: [40.39614304461201, 49.86782382165357],
    },
    {
      img: CarpetMuseumBaku,
      descImgMain: MuzeyCaroet,
      DescFirstHeydar: MiniCarpet,
      DescSecondImg: MiniCarpet2,
      id: 2,
      name: "azerbaijanCarpetMuseum",
      openClose: "openCloseCarpetMuseum",
      timeBuild: "timeBuildCarpetMuseum",
      adres: "adresCarpetMuseum",
      rooms: "roomsCarpetMuseum",
      sayt: "saytCarpetMuseum",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryCarpetMuseum",
      minihistory2: "minihistory2CarpetMuseum",
      titleDescitemTop: "titleDescitemTopCarpetMuseum",
      titleDescitemTopOpis: "titleDescitemTopOpisCarpetMuseum",
      titleDescitemBottom: "titleDescitemBottomCarpetMuseum",
      titleDescitembottomOpis: "titleDescitemBottomOpisCarpetMuseum",
      position: [40.36006057581039, 49.835759424140555],
    },
    {
      img: ArtMuseum,
      descImgMain: MuzeyArtMain,
      DescFirstHeydar: MuzeyArtMainItem,
      id: 3,
      name: "artmuseumName",
      openClose: "artopenClose",
      timeBuild: "arttimeBuild",
      adres: "artadres",
      rooms: "artrooms",
      sayt: "artsayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      special: "museums",
      specialization: "Музей",
      minihistory: "artminihistory",
      minihistory2: "artminihistory2",
      titleDescitemTop: "arttitleDescitemTop",
      titleDescitemTopOpis: "arttitleDescitemTopOpis",
      position: [40.37817895990095, 49.864734698999804],
    },
    {
      img: MiniBook,
      descImgMain: MiniBookArtMain,
      DescFirstHeydar: MiniBookArtMainItem,
      DescSecondImg: MiniBookArtMainItem2,
      id: 4,
      name: "bakuMiniBookMuseum",
      openClose: "openCloseMiniBookMuseum",
      timeBuild: "timeBuildMiniBookMuseum",
      adres: "adresMiniBookMuseum",
      rooms: "roomsMiniBookMuseum",
      sayt: "saytMiniBookMuseum",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryMiniBookMuseum",
      minihistory2: "minihistory2MiniBookMuseum",
      titleDescitemTop: "titleDescitemTopMiniBookMuseum",
      titleDescitemTopOpis: "titleDescitemTopOpisMiniBookMuseum",
      titleDescitemBottom: "titleDescitemBottomMiniBookMuseum",
      titleDescitembottomOpis: "titleDescitemBottomOpisMiniBookMuseum",
      position: [40.36654555921063, 49.83269150084628],
    },
    {
      img: YaratMusey,
      descImgMain: YaratMain,
      DescFirstHeydar: YaratDesc,
      id: 5,
      special: "museums",
      name: "yaratContemporaryArt",
      openClose: "openCloseYarat",
      timeBuild: "timeBuildYarat",
      adres: "adresYarat",
      cost: "costYarat",
      rooms: "roomsYarat",
      sayt: "saytYarat",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      specialization: "Музей",
      minihistory: "minihistoryYarat1",
      minihistory2: "minihistoryYarat2",
      titleDescitemTop: "titleDescitemTopYarat",
      titleDescitemTopOpis: "titleDescitemTopOpisYarat",
      position: [40.33958794881875, 49.837389352975045],
    },
    {
      img: FireXram,
      descImgMain: AteshgaxMain,
      DescFirstHeydar: AteshgaxDesc2,
      DescSecondImg: AteshgaxDesc,
      id: 6,
      name: "fireTempleAteshgah",
      openClose: "openCloseFireTempleAteshgah",
      timeBuild: "timeBuildFireTempleAteshgah",
      adres: "adresFireTempleAteshgah",
      rooms: "roomsFireTempleAteshgah",
      sayt: "saytFireTempleAteshgah",
      cost: "costfireTempleAteshgah",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryFireTempleAteshgah",
      minihistory2: "minihistory2FireTempleAteshgah",
      titleDescitemTop: "titleDescitemTopFireTempleAteshgah",
      titleDescitemTopOpis: "titleDescitemTopOpisFireTempleAteshgah",
      titleDescitemBottom: "titleDescitemBottomFireTempleAteshgah",
      titleDescitembottomOpis: "titleDescitemBottomOpisFireTempleAteshgah",
      position: [40.41610108337718, 50.00915412783666],
    },
    {
      img: NationalMusey,
      descImgMain: NationalMuseyMain,
      DescFirstHeydar: NationalMuseyInside,
      DescSecondImg: NationalMuseyExtra,
      id: 7,
      name: "nationalMuseumHistoryAzerbaijan",
      openClose: "openCloseNationalMuseum",
      timeBuild: "timeBuildNationalMuseum",
      adres: "adresNationalMuseum",
      rooms: "roomsNationalMuseum",
      sayt: "saytNationalMuseum",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryNationalMuseum1",
      minihistory2: "minihistoryNationalMuseum2",
      titleDescitemTop: "titleDescitemTopNationalMuseum",
      titleDescitemTopOpis: "titleDescitemTopOpisNationalMuseum",
      titleDescitemBottom: "titleDescitemBottomNationalMuseum",
      titleDescitembottomOpis: "titleDescitemBottomOpisNationalMuseum",
      position: [40.3696695277519, 49.840055524140986],
    },
    {
      img: Literaturi,
      descImgMain: LiteraturiMain,
      DescFirstHeydar: LiteraturiInside,
      DescSecondImg: LiteraturiExtra,
      id: 8,
      name: "museumAzerbaijanLiterature",
      openClose: "openCloseLiteratureMuseum",
      timeBuild: "timeBuildLiteratureMuseum",
      adres: "adresLiteratureMuseum",
      rooms: "roomsLiteratureMuseum",
      sayt: "saytLiteratureMuseum",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryLiteratureMuseum1",
      minihistory2: "minihistoryLiteratureMuseum2",
      titleDescitemTop: "titleDescitemTopLiteratureMuseum",
      titleDescitemTopOpis: "titleDescitemTopOpisLiteratureMuseum",
      titleDescitemBottom: "titleDescitemBottomLiteratureMuseum",
      titleDescitembottomOpis: "titleDescitemBottomOpisLiteratureMuseum",
      position: [40.3699338121695, 49.8365194468696],
    },
    {
      img: CentralMusei,
      descImgMain: CentralMuseiMain,
      DescFirstHeydar: CentralMuseiInside,
      id: 9,
      name: "museumCenter",
      openClose: "openCloseMuseumCenter",
      timeBuild: "timeBuildMuseumCenter",
      adres: "adresMuseumCenter",
      rooms: "roomsMuseumCenter",
      sayt: "saytMuseumCenter",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryMuseumCenter1",
      minihistory2: "minihistoryMuseumCenter2",
      titleDescitemTop: "titleDescitemTopMuseumCenter",
      titleDescitemTopOpis: "titleDescitemTopOpisMuseumCenter",
      titleDescitemBottom: "titleDescitemBottomMuseumCenter",
      titleDescitembottomOpis: "titleDescitemBottomOpisMuseumCenter",
      position: [40.369669008238624, 49.843097552410285],
    },
    {
      img: IsteglalMusei,
      descImgMain: IsteglalMuseiMain,
      DescFirstHeydar: IsteglalMuseiInside,
      id: 10,
      name: "independenceMuseum",
      openClose: "openCloseIndependenceMuseum",
      timeBuild: "timeBuildIndependenceMuseum",
      adres: "adresIndependenceMuseum",
      rooms: "roomsIndependenceMuseum",
      sayt: "saytIndependenceMuseum",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistoryIndependenceMuseum1",
      minihistory2: "minihistoryIndependenceMuseum2",
      titleDescitemTop: "titleDescitemTopIndependenceMuseum",
      titleDescitemTopOpis: "titleDescitemTopOpisIndependenceMuseum",
      titleDescitemBottom: "titleDescitemBottomIndependenceMuseum",
      titleDescitembottomOpis: "titleDescitemBottomOpisIndependenceMuseum",
      position: [40.369751268695715, 49.842415867900364],
    },
    {
      img: VurgunOlace,
      descImgMain: VurgunOlaceMain,
      DescFirstHeydar: VurgunOlaceInside,
      id: 11,
      name: "samedVurghunHouseMuseum",
      openClose: "openCloseSamedVurghun",
      timeBuild: "timeBuildSamedVurghun",
      adres: "adresSamedVurghun",
      sayt: "saytSamedVurghun",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      special: "museums",
      specialization: "Музей",
      minihistory: "minihistorySamedVurghun1",
      minihistory2: "minihistorySamedVurghun2",
      titleDescitemTop: "titleDescitemTopSamedVurghun",
      titleDescitemTopOpis: "titleDescitemTopOpisSamedVurghun",
      position: [40.36891558760584, 49.83950495666997],
    },
    {
      img: UzeirHouse,
      descImgMain: HouseUzeirMuseumMain,
      DescFirstHeydar: HouseUzeirMuseumDesc,
      id: 12,
      specialization: "Музей",
      special: "museums",
      name: "uzeirName",
      openClose: "uzeirOpenClose",
      timeBuild: "uzeirTimeBuild",
      adres: "uzeirAdres",
      cost: "uzeirCost",
      rooms: "uzeirRooms",
      sayt: "uzeirSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      minihistory: "uzeirMinihistory",
      minihistory2: "uzeirMinihistory2",
      titleDescitemTop: "uzeirTitleDescitemTop",
      titleDescitemTopOpis: "uzeirTitleDescitemTopOpis",
      position: [40.37756794921273, 49.829888768317566],
    },
    {
      img: JafarJabbarliHousem,
      descImgMain: HouseJafarbliMuseumMain,
      DescFirstHeydar: HouseJafarbliMuseumDesc,
      id: 13,
      specialization: "Музей",
      special: "museums",
      name: "JabbarliName",
      openClose: "JabbarliOpenClose",
      timeBuild: "JabbarliTimeBuild",
      adres: "JabbarliAdres",
      cost: "JabbarliCost",
      rooms: "JabbarliRooms",
      sayt: "JabbarliSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      minihistory: "JabbarliMiniHistory1",
      minihistory2: "JabbarliMiniHistory2",
      titleDescitemTop: "JabbarliTitleDescTop",
      titleDescitemTopOpis: "JabbarliTitleDescOpis",
      position: [40.36800401727344, 49.82204186831723],
    },
    {
      img: GanjaHistory,
      descImgMain: GanjaHistoryMain,
      DescFirstHeydar: GanjaHistoryDesc,
      id: 14,
      specialization: "Музей",
      special: "museums",
      name: "GanjaHistoryName",
      openClose: "GanjaHistoryOpenClose",
      timeBuild: "GanjaHistoryTimeBuild",
      adres: "GanjaHistoryAdres",
      cost: "GanjaHistoryCost",
      rooms: "GanjaHistoryRooms",
      sayt: "GanjaHistorySayt",
      category: "Gəncə",
      city: "Ganja",
      specialTranslate: "museums",
      minihistory: "GanjaHistoryMiniHistory1",
      minihistory2: "GanjaHistoryMiniHistory2",
      titleDescitemTop: "GanjaHistoryTitleDescTop",
      titleDescitemTopOpis: "GanjaHistoryTitleDescOpis",
      position: [40.68016505301273, 46.35785224318801],
    },
    {
      img: MuzeyGandjs,
      descImgMain: GanjaMuseumMain,
      DescFirstHeydar: GanjaMuseumDesc,
      id: 15,
      specialization: "Музей",
      special: "museums",
      name: "HeydarGanjaName",
      openClose: "HeydarGanjaOpenClose",
      timeBuild: "HeydarGanjaTimeBuild",
      adres: "HeydarGanjaAdres",
      cost: "HeydarGanjaCost",
      rooms: "HeydarGanjaRooms",
      sayt: "GanjaHistorySayt",
      category: "Gəncə",
      city: "Ganja",
      specialTranslate: "museums",
      minihistory: "HeydarGanjaMiniHistory1",
      minihistory2: "HeydarGanjaMiniHistory2",
      titleDescitemTop: "HeydarGanjaTitleDescTop",
      titleDescitemTopOpis: "HeydarGanjaTitleDescOpis",
      position: [40.68082566225776, 46.36008225028516],
    },
    {
      img: ShekiMuzet,
      descImgMain: ShekiSareyMain,
      DescFirstHeydar: ShekiSareyDesc,
      id: 16,
      specialization: "Музей",
      special: "museums",
      name: "ShekiPalaceName",
      openClose: "ShekiPalaceOpenClose",
      timeBuild: "ShekiPalaceTimeBuild",
      adres: "ShekiPalaceAdres",
      cost: "ShekiPalaceCost",
      rooms: "HeydarGanjaRooms",
      sayt: "ShekiPalaceSayt",
      category: "Şəki",
      city: "Sheki",
      specialTranslate: "museums",
      minihistory: "ShekiPalaceMiniHistory1",
      minihistory2: "ShekiPalaceMiniHistory2",
      titleDescitemTop: "ShekiPalaceTitleDescTop",
      titleDescitemTopOpis: "ShekiPalaceTitleDescOpis",
      position: [41.20480551995459, 47.19760081730093],
    },
    {
      img: ShekiMuzeyKravoed,
      descImgMain: ShekiTarixMain,
      DescFirstHeydar: ShekiTarixDesc,
      id: 17,
      specialization: "Музей",
      special: "Музей",
      name: "ShekiLocalMuseumName",
      openClose: "ShekiLocalMuseumOpenClose",
      timeBuild: "ShekiLocalMuseumTimeBuild",
      adres: "ShekiLocalMuseumAdres",
      cost: "ShekiLocalMuseumCost",
      rooms: "ShekiLocalMuseumRooms",
      sayt: "ShekiLocalMuseumSayt",
      category: "Şəki",
      city: "Sheki",
      specialTranslate: "museums",
      minihistory: "ShekiLocalMuseumMiniHistory1",
      minihistory2: "ShekiLocalMuseumMiniHistory2",
      titleDescitemTop: "ShekiLocalMuseumTitleDescTop",
      titleDescitemTopOpis: "ShekiLocalMuseumTitleDescOpis",
      position: [41.203765764171216, 47.195549793492106],
    },
    {
      img: LankoranMuzey,
      descImgMain: LankaranMuseyMain,
      DescFirstHeydar: LankaranMuseyDesc,
      id: 18,
      specialization: "Музей",
      special: "Музей",
      name: "LankoranHouseName",
      openClose: "LankoranHouseOpenClose",
      timeBuild: "LankoranHouseTimeBuild",
      adres: "LankoranHouseAdres",
      cost: "LankoranHouseCost",
      rooms: "LankoranHouseRooms",
      sayt: "LankoranHouseSayt",
      category: "Lənkəran",
      city: "Lankaran",
      specialTranslate: "museums",
      minihistory: "LankoranHouseMiniHistory1",
      minihistory2: "LankoranHouseMiniHistory2",
      titleDescitemTop: "LankoranHouseTitleDescTop",
      titleDescitemTopOpis: "LankoranHouseTitleDescOpis",
      position: [38.7540477963439, 48.856374136045645],
    },
    {
      img: LankoranHaziMuzey,
      descImgMain: LankaranEzizMain,
      DescFirstHeydar: LankaranEzizDesc,
      id: 19,
      specialization: "Музей",
      special: "Музей",
      name: "LankoranAslanovHouseName",
      openClose: "LankoranAslanovHouseOpenClose",
      timeBuild: "LankoranAslanovHouseTimeBuild",
      adres: "LankoranAslanovHouseAdres",
      cost: "LankoranAslanovHouseCost",
      rooms: "LankoranAslanovHouseRooms",
      sayt: "LankoranHouseSayt",
      category: "Lənkəran",
      city: "Lankaran",
      specialTranslate: "museums",
      minihistory: "LankoranAslanovHouseMiniHistory1",
      minihistory2: "LankoranAslanovHouseMiniHistory2",
      titleDescitemTop: "LankoranAslanovHouseTitleDescTop",
      titleDescitemTopOpis: "LankoranAslanovHouseTitleDescOpis",
      position: [38.750439991815405, 48.851898483219735],
    },
    {
      img: ShamaxiMuzey,
      descImgMain: ShamaxiResedxanasiMain,
      DescFirstHeydar: ShamaxiResedxanasiDesc,
      id: 20,
      specialization: "Музей",
      special: "Музей",
      name: "observatoryName",
      openClose: "observatoryOpenClose",
      timeBuild: "observatoryTimeBuild",
      adres: "observatoryAdres",
      cost: "-",
      rooms: "observatoryRooms",
      sayt: "observatorySayt",
      category: "Şamaxı",
      city: "Shamakhi",
      specialTranslate: "museums",
      minihistory: "observatoryMinihistory",
      minihistory2: "observatoryMinihistory2",
      titleDescitemTop: "observatoryTitleDescitemTop",
      titleDescitemTopOpis: "observatoryTitleDescitemTopOpis",
      position: [40.782206809956854, 48.60034001250998],
    },
    {
      img: CarpetShusaMuzey,
      descImgMain: ShushaCarpetMuzeyMain,
      DescFirstHeydar: ShushaCarpetMuzeyDesc,
      id: 21,
      specialization: "Музей",
      special: "Музей",
      name: "carpetShusaName",
      openClose: "carpetShusaOpenClose",
      timeBuild: "carpetShusaTimeBuild",
      adres: "carpetShusaAdres",
      cost: "carpetShusaCost",
      rooms: "carpetShusaRooms",
      sayt: "LankoranHouseSayt",
      category: "Qarabağ",
      city: "Karabakh",
      specialTranslate: "museums",
      minihistory: "carpetShusaMinihistory",
      minihistory2: "carpetShusaMinihistory2",
      titleDescitemTop: "carpetShusaTitleDescitemTop",
      titleDescitemTopOpis: "carpetShusaTitleDescitemTopOpis",
      position: [39.76014783752609, 46.747271666446544],
    },
    {
      img: MavzouleyShusa,
      descImgMain: ShushaVagifMuzeyMain,
      DescFirstHeydar: ShushaVagifMuzeyDescs,
      id: 22,
      special: "Palaces",
      specialization: "Дворцы",
      name: "vagifName",
      openClose: "vagifOpenClose",
      timeBuild: "vagifTimeBuild",
      adres: "vagifAdres",
      cost: "vagifCost",
      rooms: "vagifRooms",
      sayt: "LankoranHouseSayt",
      category: "Qarabağ",
      city: "Karabakh",
      specialTranslate: "palaces",
      minihistory: "vagifMinihistory",
      minihistory2: "vagifMinihistory2",
      titleDescitemTop: "vagifTitleDescitemTop",
      titleDescitemTopOpis: "vagifTitleDescitemTopOpis",
      position: [39.75555149710669, 46.75828118178732],
    },
    {
      img: BulBulMuzeyShusha,
      descImgMain: BulBulMuzeyShushaMain,
      DescFirstHeydar: BulBulMuzeyShushaDesc,
      id: 23,
      specialization: "Музей",
      special: "Музей",
      name: "bulbulName",
      openClose: "bulbulOpenClose",
      timeBuild: "bulbulTimeBuild",
      adres: "bulbulAdres",
      cost: "bulbulCost",
      rooms: "bulbulRooms",
      sayt: "-",
      category: "Qarabağ",
      city: "Karabakh",
      specialTranslate: "museums",
      minihistory: "bulbulMinihistory",
      minihistory2: "bulbulMinihistory2",
      titleDescitemTop: "bulbulTitleDescitemTop",
      titleDescitemTopOpis: "bulbulTitleDescitemTopOpis",
      position: [40.37396883760093, 49.84409356036397],
    },
    {
      img: GabalaGeologCenter,
      descImgMain: GabalaGeologCenterMain,
      DescFirstHeydar: GabalaGeologCenterDesc,
      id: 24,
      specialization: "Музей",
      special: "Музей",
      name: "gabalaName",
      openClose: "gabalaOpenClose",
      timeBuild: "gabalaTimeBuild",
      adres: "gabalaAdres",
      cost: "gabalaCost",
      rooms: "bulbulRooms",
      category: "Qəbələ",
      city: "Gabala",
      specialTranslate: "museums",
      minihistory: "gabalaMinihistory",
      minihistory2: "gabalaMinihistory2",
      titleDescitemTop: "gabalaTitleDescitemTop",
      titleDescitemTopOpis: "gabalaTitleDescitemTopOpis",
      position: [40.88956569220364, 47.693500750163025],
    },
    {
      img: GabalaKraevodMuzey,
      descImgMain: GabalaKraevodMuzeyMain,
      DescFirstHeydar: GabalaKraevodMuzeyDesc,
      id: 25,
      specialization: "Музей",
      special: "Музей",
      name: "gabalaKraevoName",
      openClose: "gabalaKraevoOpenClose",
      timeBuild: "gabalaKraevoTimeBuild",
      adres: "gabalaKraevoAdres",
      cost: "gabalaKraevoCost",
      rooms: "gabalaKraevoRooms",
      category: "Qəbələ",
      city: "Gabala",
      specialTranslate: "museums",
      minihistory: "gabalaKraevoMinihistory",
      minihistory2: "gabalaKraevoMinihistory2",
      titleDescitemTop: "gabalaKraevoTitleDescitemTop",
      titleDescitemTopOpis: "gabalaKraevoTitleDescitemTopOpis",
      position: [39.76014783752609, 46.747271666446544],
    },
    {
      img: XacmazMuzeum,
      descImgMain: XacmazMuzeumMain,
      DescFirstHeydar: XacmazMuzeumDesc,
      id: 26,
      specialization: "Музей",
      special: "Музей",
      name: "xachmazName",
      openClose: "xachmazOpenClose",
      timeBuild: "xachmazTimeBuild",
      adres: "xachmazAdres",
      cost: "xachmazCost",
      rooms: "xachmazRooms",
      category: "Xaçmaz",
      city: "Khachmaz",
      specialTranslate: "museums",
      minihistory: "xachmazMinihistory",
      minihistory2: "xachmazMinihistory2",
      titleDescitemTop: "xachmazTitleDescitemTop",
      titleDescitemTopOpis: "xachmazTitleDescitemTopOpis",
      position: [41.465667598880366, 48.805482435340465],
    },
    {
      img: MuzeumXacmaxfreinds,
      descImgMain: XacmazMuzeumMain,
      DescFirstHeydar: XacmazMuzeumFreindsDesc,
      id: 28,
      specialization: "Музей",
      special: "Музей",
      name: "xachmazFriendsName",
      openClose: "xachmazFriendsOpenClose",
      timeBuild: "xachmazFriendsTimeBuild",
      adres: "xachmazFriendsAdres",
      cost: "xachmazFriendsCost",
      rooms: "xachmazFriendsRooms",
      category: "Xaçmaz",
      city: "Khachmaz",
      specialTranslate: "museums",
      minihistory: "xachmazFriendsMinihistory",
      minihistory2: "xachmazFriendsMinihistory2",
      titleDescitemTop: "xachmazFriendsTitleDescitemTop",
      titleDescitemTopOpis: "xachmazFriendsTitleDescitemTopOpis",
      position: [41.465843287872325, 48.805422234720055],
    },
    {
      img: XacmazCarpetMuzeum,
      descImgMain: XacmazCarpetMain,
      DescFirstHeydar: XacmazCarpetDesc,
      id: 29,
      specialization: "Музей",
      special: "Музей",
      name: "xachmazCarpetName",
      openClose: "xachmazCarpetOpenClose",
      timeBuild: "xachmazCarpetTimeBuild",
      adres: "xachmazCarpetAdres",
      cost: "xachmazCarpetCost",
      rooms: "xachmazCarpetRooms",
      category: "Xaçmaz",
      city: "Khachmaz",
      specialTranslate: "museums",
      minihistory: "xachmazCarpetMinihistory",
      minihistory2: "xachmazCarpetMinihistory2",
      titleDescitemTop: "xachmazCarpetTitleDescitemTop",
      titleDescitemTopOpis: "xachmazCarpetTitleDescitemTopOpis",
      position: [41.465192072170105, 48.800696182783675],
    },
    {
      img: ShamkirMuzey,
      descImgMain: ShamkirMuzeyMain,
      DescFirstHeydar: ShamkirMuzeyDesc,
      id: 30,
      special: "museums",
      specialization: "Музей",
      name: "ShamkirMuseumName",
      openClose: "ShamkirMuseumOpenClose",
      timeBuild: "ShamkirMuseumTimeBuild",
      adres: "ShamkirMuseumAdres",
      cost: "ShamkirMuseumCost",
      rooms: "ShamkirMuseumRooms",
      sayt: "-",
      category: "Şəmkir",
      city: "Shamkir",
      specialTranslate: "museums",
      minihistory: "ShamkirMuseumMiniHistory1",
      minihistory2: "ShamkirMuseumMiniHistory2",
      titleDescitemTop: "ShamkirMuseumTitleDesc",
      titleDescitemTopOpis: "ShamkirMuseumTitleDescOpis",
      position: [40.833590426646936, 46.02476710296071],
    },
    // Attractive
    // Attractive Baku
    {
      img: SeeBreez,
      descImgMain: SeeBreezMain,
      DescFirstHeydar: SeeBreezF,
      id: 31,
      special: "attractive",
      specialization: "Attractive",
      name: "seaBreeze",
      openClose: "openCloseSeaBreeze",
      timeBuild: "timeBuildSeaBreeze",
      adres: "adresSeaBreeze",
      // cost: "-",
      // rooms: "roomsSeaBreeze",
      sayt: "saytSeaBreeze",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "minihistorySeaBreeze",
      minihistory2: "minihistory2SeaBreeze",
      position: [40.582312074926946, 49.94406779295458],
      titleDescitemTop: "titleDescitemTopSeaBreeze",
      titleDescitemTopOpis: "titleDescitemTopOpisSeaBreeze",
    },
    {
      img: SkyPark,
      descImgMain: SkyParkMain,
      DescFirstHeydar: SkyParkZone,
      id: 32,
      name: "SkyPark",
      openClose: "openCloseSkyPark",
      timeBuild: "timeBuildSkyPark",
      adres: "adresSkyPark",
      cost: "costSkyPark",
      rooms: "roomsSkyPark",
      sayt: "saytSkyPark",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      special: "attractive",
      specialization: "Attractive",
      minihistory: "minihistorySkyPark1",
      minihistory2: "minihistorySkyPark2",
      titleDescitemTop: "titleDescitemTopSkyPark",
      titleDescitemTopOpis: "titleDescitemTopOpisSkyPark",
      position: [40.35818252243587, 49.83753617016377],
    },
    {
      img: VrPark,
      descImgMain: VrParkMain,
      DescFirstHeydar: VrParkDesc,
      id: 33,
      name: "vrPark",
      openClose: "openCloseVRPark",
      timeBuild: "timeBuildVRPark",
      adres: "adresVRPark",
      cost: "20–27 AZN",
      // rooms: "roomsSkyPark",
      sayt: "saytVRPark",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      special: "attractive",
      specialization: "Attractive",
      minihistoryVRPark1: "minihistorySkyPark1",
      minihistoryVRPark2: "minihistorySkyPark2",
      titleDescitemTopVRPark: "titleDescitemTopSkyPark",
      titleDescitemTopOpisVRPark: "titleDescitemTopOpisSkyPark",
      position: [40.378783490431765, 49.87593738550576],
    },
    {
      img: ShootingPark,
      descImgMain: ShootingMain,
      DescFirstHeydar: ShootingMainDesc,
      DescSecondImg: ShootingMainDesc2,
      id: 34,
      special: "attractive",
      specialization: "Attractive",
      name: "nameBakuShooting",
      openClose: "openCloseBakuShooting",
      timeBuild: "timeBuildBakuShooting",
      adres: "adresBakuShooting",
      cost: "costBakuShooting",
      rooms: "roomsBakuShooting",
      sayt: "-",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "minihistoryBakuShooting1",
      minihistory2: "minihistoryBakuShooting2",
      titleDescitemTop: "titleDescitemTopBakuShooting",
      titleDescitemTopOpis: "titleDescitemTopOpisBakuShooting",
      titleDescitemBottom: "titleDescitemBottom",
      titleDescitembottomOpis: "titleDescitembottomOpis",
      position: [40.41335624664135, 49.790497324142756],
    },
    {
      img: HorseClub,
      descImgMain: HorseClubMain,
      DescFirstHeydar: HorseClubDesc1,
      id: 35,
      special: "attractive",
      specialization: "Attractive",
      name: "HorseClubname",
      openClose: "openCloseHorseClub",
      timeBuild: "timeBuildHorseClub",
      adres: "adresHorseClub",
      cost: "costHorseClub",
      rooms: "roomsHorseClub",
      sayt: "-",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "minihistoryHorseClub1",
      minihistory2: "minihistoryHorseClub2",
      titleDescitemTop: "titleDescitemTopHorseClub",
      titleDescitemTopOpis: "titleDescitemTopOpisHorseClub",
      position: [40.465268896411345, 50.084903275708484],
    },
    {
      img: Karting,
      descImgMain: KartingMain,
      DescFirstHeydar: KartingDesc1,
      id: 36,
      special: "attractive",
      specialization: "Attractive",
      name: "KartingName",
      openClose: "KartingOpenClose",
      timeBuild: "KartingTimeBuild",
      adres: "KartingAdres",
      cost: "KartingCost",
      rooms: "KartingRooms",
      sayt: "KartingSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "KartingMiniHistory1",
      minihistory2: "KartingMiniHistory2",
      titleDescitemTop: "KartingTitleDescTop",
      titleDescitemTopOpis: "KartingTitleDescOpis",
      position: [40.4197524673782, 49.854258539483936],
    },
    {
      img: Waterpark,
      descImgMain: WaterparkMain,
      DescFirstHeydar: WaterparkDesc1,
      id: 37,
      special: "attractive",
      specialization: "Attractive",
      name: "WaterparkName",
      openClose: "WaterparkOpenClose",
      timeBuild: "WaterparkTimeBuild",
      adres: "WaterparkAdres",
      cost: "WaterparkCost",
      rooms: "WaterparkRooms",
      sayt: "WaterparkSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "WaterparkMiniHistory1",
      minihistory2: "WaterparkMiniHistory2",
      titleDescitemTop: "WaterparkTitleDescTop",
      titleDescitemTopOpis: "WaterparkTitleDescOpis",
      position: [40.5896431467394, 50.06437546320031],
    },
    {
      img: ZireZig,
      descImgMain: ZireZigMain,
      DescFirstHeydar: ZireZigDesc,
      id: 38,
      special: "attractive",
      specialization: "Attractive",
      name: "ZireExtremeName",
      openClose: "ZireExtremeOpenClose",
      timeBuild: "ZireExtremeTimeBuild",
      adres: "ZireExtremeAdres",
      cost: "ZireExtremeCost",
      rooms: "ZireExtremeRooms",
      sayt: "ZireExtremeSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "ZireExtremeMinihistory",
      minihistory2: "ZireExtremeMinihistory2",
      titleDescitemTop: "ZireExtremeTitleDescitemTop",
      titleDescitemTopOpis: "ZireExtremeTitleDescitemTopOpis",
      position: [40.40860629815081, 50.29764468764973],
    },
    {
      img: BakuClimbingGym,
      descImgMain: BakuClimbingGymMain,
      DescFirstHeydar: BakuClimbingGymDesc,
      id: 39,
      special: "attractive",
      specialization: "Attractive",
      name: "ClimbingGymName",
      openClose: "ClimbingGymOpenClose",
      timeBuild: "ClimbingGymTimeBuild",
      adres: "ClimbingGymAdres",
      cost: "ClimbingGymCost",
      rooms: "ClimbingGymRooms",
      sayt: "ClimbingGymSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "ClimbingGymMinihistory",
      minihistory2: "ClimbingGymMinihistory2",
      titleDescitemTop: "ClimbingGymTitleDescitemTop",
      titleDescitemTopOpis: "ClimbingGymTitleDescitemTopOpis",
      position: [40.37820114060415, 49.89823211618776],
    },
    {
      img: BakuEye,
      descImgMain: BakuEyeMain,
      DescFirstHeydar: BakuEyeDesc,
      id: 40,
      special: "attractive",
      specialization: "Attractive",
      name: "BakuEyeName",
      openClose: "BakuEyeOpenClose",
      timeBuild: "BakuEyeTimeBuild",
      adres: "BakuEyeAdres",
      cost: "BakuEyeCost",
      rooms: "BakuEyeRooms",
      sayt: "BakuEyeSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "BakuEyeMinihistory",
      minihistory2: "BakuEyeMinihistory2",
      titleDescitemTop: "BakuEyeTitleDescitemTop",
      titleDescitemTopOpis: "BakuEyeTitleDescitemTopOpis",
      position: [40.35478258605121, 49.83763892783404],
    },
    {
      img: DalgaBeach,
      descImgMain: DalgaBeachMain,
      DescFirstHeydar: DalgaBeachDesc,
      id: 41,
      special: "attractive",
      specialization: "Attractive",
      name: "DalgaBeachName",
      openClose: "DalgaBeachOpenClose",
      timeBuild: "DalgaBeachTimeBuild",
      adres: "DalgaBeachAdres",
      cost: "DalgaBeachCost",
      rooms: "DalgaBeachRooms",
      sayt: "DalgaBeachSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "DalgaBeachMinihistory",
      minihistory2: "DalgaBeachMinihistory2",
      titleDescitemTop: "DalgaBeachTitleDescitemTop",
      titleDescitemTopOpis: "DalgaBeachTitleDescitemTopOpis",
      position: [40.51227922076515, 50.16744499900515],
    },
    {
      img: Bowling,
      descImgMain: BowlingMain,
      DescFirstHeydar: BowlingDesc,
      id: 42,
      special: "attractive",
      specialization: "Attractive",
      name: "BowlingName",
      openClose: "BowlingOpenClose",
      timeBuild: "BowlingTimeBuild",
      adres: "BowlingAdres",
      cost: "BowlingCost",
      rooms: "BowlingRooms",
      sayt: "BowlingSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "BowlingMinihistory",
      minihistory2: "BowlingMinihistory2",
      titleDescitemTop: "BowlingTitleDescitemTop",
      titleDescitemTopOpis: "BowlingTitleDescitemTopOpis",
      position: [40.37691787789518, 49.84130423353565],
    },
    // Attractive Qusar
    {
      img: Shagdag,
      descImgMain: ShagdagMain,
      DescFirstHeydar: ShagdagMainDesc,
      DescSecondImg: ShagdagMainDesc2,
      id: 43,
      special: "attractive",
      specialization: "Attractive",
      name: "ShahdagName",
      openClose: "ShahdagOpenClose",
      timeBuild: "ShahdagTimeBuild",
      adres: "ShahdagAdres",
      cost: "ShahdagCost",
      rooms: "ShahdagRooms",
      sayt: "ShahdagSayt",
      category: "Qarışıq yerlər",
      city: "Shaxdag",
      specialTranslate: "Entertainment",
      minihistory: "ShahdagMinihistory",
      minihistory2: "ShahdagMinihistory2",
      titleDescitemTop: "ShahdagTitleDescitemTop",
      titleDescitemTopOpis: "ShahdagTitleDescitemTopOpis",
      titleDescitemBottom: "ShahdagTitleDescitemBottom",
      titleDescitembottomOpis: "ShahdagTitleDescitemBottomOpis",
      position: [40.07626112747628, 49.414580184785265],
    },
    // Attractive Qobustan
    {
      img: Safari,
      descImgMain: SafariMain,
      DescFirstHeydar: SafariMainDesc,
      DescSecondImg: SafariMainDesc2,
      id: 44,
      special: "attractive",
      specialization: "Attractive",
      name: "QobustanSafariName",
      openClose: "QobustanSafariOpenClose",
      timeBuild: "QobustanSafariTimeBuild",
      adres: "QobustanSafariAdres",
      cost: "QobustanSafariCost",
      rooms: "QobustanSafariRooms",
      sayt: "QobustanSafariSayt",
      category: "Qobustan",
      city: "Gobustan",
      specialTranslate: "Entertainment",
      minihistory: "QobustanSafariMinihistory",
      minihistory2: "QobustanSafariMinihistory2",
      titleDescitemTop: "QobustanSafariTitleDescitemTop",
      titleDescitemTopOpis: "QobustanSafariTitleDescitemTopOpis",
      titleDescitemBottom: "QobustanSafariTitleDescitemBottom",
      titleDescitembottomOpis: "QobustanSafariTitleDescitemBottomOpis",
      position: [41.00252455558901, 47.87817116649553],
    },
    // Attractive Qabala
    {
      img: Gabalalnd,
      descImgMain: GabalalanfMain,
      DescFirstHeydar: GabalalanfDesc,
      id: 45,
      special: "attractive",
      specialization: "Attractive",
      name: "GabalandName",
      openClose: "GabalandOpenClose",
      timeBuild: "GabalandTimeBuild",
      adres: "GabalandAdres",
      cost: "GabalandCost",
      rooms: "GabalandRooms",
      sayt: "GabalandSayt",
      category: "Qəbələ",
      city: "Gabala",
      specialTranslate: "Entertainment",
      minihistory: "GabalandMinihistory",
      minihistory2: "GabalandMinihistory2",
      titleDescitemTop: "GabalandTitleDescitemTop",
      titleDescitemTopOpis: "GabalandTitleDescitemTopOpis",
      position: [41.00252455558901, 47.87817116649553],
    },
    {
      img: GabalaShooting,
      descImgMain: GabalaShootingMain,
      DescFirstHeydar: GabalaShootingDesc,
      id: 46,
      special: "attractive",
      specialization: "Attractive",
      name: "GabalaShootingName",
      openClose: "GabalaShootingOpenClose",
      timeBuild: "GabalaShootingTimeBuild",
      adres: "GabalaShootingAdres",
      cost: "GabalaShootingCost",
      rooms: "GabalaShootingRooms",
      sayt: "GabalaShootingSayt",
      category: "Qəbələ",
      city: "Gabala",
      specialTranslate: "Entertainment",
      minihistory: "GabalaShootingMinihistory",
      minihistory2: "GabalaShootingMinihistory2",
      titleDescitemTop: "GabalaShootingTitleDescitemTop",
      titleDescitemTopOpis: "GabalaShootingTitleDescitemTopOpis",
      position: [41.00458134752198, 47.80124223766034],
    },
    // Attraction Ganja
    {
      img: GanjaPaintBall,
      descImgMain: GanjaPaintMain,
      DescFirstHeydar: GanjaPaintDesc,
      id: 47,
      special: "attractive",
      specialization: "Attractive",
      name: "GanjaPaintballName",
      openClose: "GanjaPaintballOpenClose",
      timeBuild: "GanjaPaintballTimeBuild",
      adres: "GanjaPaintballAdres",
      cost: "GanjaPaintballCost",
      rooms: "GanjaPaintballRooms",
      sayt: "GanjaPaintballSayt",
      category: "Gəncə",
      city: "Ganja",
      specialTranslate: "Entertainment",
      minihistory: "GanjaPaintballMinihistory",
      minihistory2: "GanjaPaintballMinihistory2",
      titleDescitemTop: "GanjaPaintballTitleDescitemTop",
      titleDescitemTopOpis: "GanjaPaintballTitleDescitemTopOpis",
      position: [40.683722379060875, 46.402058956682424],
    },
    // Attraction Goygol
    {
      img: GoyGolOffRoad,
      descImgMain: GoyGolOffRoadMain,
      DescFirstHeydar: GoyGolOffRoadDesc,
      id: 48,
      special: "attractive",
      specialization: "Attractive",
      name: "GoygolOffRoadName",
      openClose: "GoygolOffRoadOpenClose",
      timeBuild: "GoygolOffRoadTimeBuild",
      adres: "GoygolOffRoadAdres",
      cost: "GoygolOffRoadCost",
      rooms: "GoygolOffRoadRooms",
      sayt: "GoygolOffRoadSayt",
      category: "Gəncə",
      city: "Ganja",
      specialTranslate: "Entertainment",
      minihistory: "GoygolOffRoadMinihistory",
      minihistory2: "GoygolOffRoadMinihistory2",
      titleDescitemTop: "GoygolOffRoadTitleDescitemTop",
      titleDescitemTopOpis: "GoygolOffRoadTitleDescitemTopOpis",
      position: [40.58692241910394, 46.315861141337464],
    },
    // Attraction Lankaran
    {
      img: AquaParkNovyyLankaran,
      descImgMain: LankaranMain,
      DescFirstHeydar: LankaranDesc,
      id: 49,
      special: "attractive",
      specialization: "Attractive",
      name: "LankaranAquaName",
      openClose: "LankaranAquaOpenClose",
      timeBuild: "LankaranAquaTimeBuild",
      adres: "LankaranAquaAdres",
      cost: "LankaranAquaCost",
      rooms: "LankaranAquaRooms",
      sayt: "LankaranAquaSayt",
      category: "Lənkəran",
      city: "Lankaran",
      specialTranslate: "Entertainment",
      minihistory: "LankaranAquaMinihistory",
      minihistory2: "LankaranAquaMinihistory2",
      titleDescitemTop: "LankaranAquaTitleDescitemTop",
      titleDescitemTopOpis: "LankaranAquaTitleDescitemTopOpis",
      position: [38.762917269887, 48.84791142167508],
    },
    // Nation
    // Nation Qabala
    {
      img: NohurLake,
      descImgMain: NohurLakeMain,
      DescFirstHeydar: NohurLakeDesc,
      id: 50,
      special: "nature",
      specialization: "nature",
      name: "NohurLakeName",
      openClose: "NohurLakeOpenClose",
      timeBuild: "NohurLakeTimeBuild",
      adres: "NohurLakeAdres",
      cost: "NohurLakeCost",
      rooms: "NohurLakeRooms",
      sayt: "NohurLakeSayt",
      category: "Qəbələ",
      city: "Gabala",
      specialTranslate: "nature",
      minihistory: "NohurLakeMinihistory",
      minihistory2: "NohurLakeMinihistory2",
      titleDescitemTop: "NohurLakeTitleDescitemTop",
      titleDescitemTopOpis: "NohurLakeTitleDescitemTopOpis",
      position: [40.960228854660116, 47.88241978028162],
    },
    // Nation GoyGol
    {
      img: GoyGolLake,
      descImgMain: GoyGolMain,
      DescFirstHeydar: GoyGolDesc,
      id: 51,
      special: "nature",
      specialization: "nature",
      name: "GoyGolLakeName",
      openClose: "GoyGolLakeOpenClose",
      timeBuild: "GoyGolLakeTimeBuild",
      adres: "GoyGolLakeAdres",
      cost: "GoyGolLakeCost",
      rooms: "GoyGolLakeRooms",
      sayt: "GoyGolLakeSayt",
      category: "Gəncə",
      city: "Ganja",
      specialTranslate: "nature",
      minihistory: "GoyGolLakeMinihistory",
      minihistory2: "GoyGolLakeMinihistory2",
      titleDescitemTop: "GoyGolLakeTitleDescitemTop",
      titleDescitemTopOpis: "GoyGolLakeTitleDescitemTopOpis",
      position: [40.37719373739168, 46.3000380891994],
    },
    // Nature QAX
    {
      img: IlisuVilage,
      descImgMain: IlisuMain,
      DescFirstHeydar: IlisuDesc,
      id: 52,
      special: "nature",
      specialization: "nature",
      name: "IlisuVilageName",
      openClose: "IlisuVilageOpenClose",
      timeBuild: "IlisuVilageTimeBuild",
      adres: "IlisuVilageAdres",
      cost: "IlisuVilageCost",
      rooms: "IlisuVilageRooms",
      sayt: "IlisuVilageSayt",
      category: "Qarışıq yerlər",
      // city: "Ganja",
      specialTranslate: "nature",
      minihistory: "IlisuVilageMinihistory",
      minihistory2: "IlisuVilageMinihistory2",
      titleDescitemTop: "IlisuVilageTitleDescitemTop",
      titleDescitemTopOpis: "IlisuVilageTitleDescitemTopOpis",
      position: [41.468650007305015, 47.057146999383455],
    },
    // Nature Ismayilli
    {
      img: LahicNature,
      descImgMain: LahicMain,
      DescFirstHeydar: LahicDesc,
      id: 53,
      special: "nature",
      specialization: "nature",
      name: "LahijVillageName",
      openClose: "LahijVillageOpenClose",
      timeBuild: "LahijVillageTimeBuild",
      adres: "LahijVillageAdres",
      cost: "LahijVillageCost",
      rooms: "LahijVillageRooms",
      sayt: "LahijVillageSayt",
      category: "Ismayilli",
      city: "Ismailli",
      specialTranslate: "nature",
      minihistory: "LahijVillageMinihistory",
      minihistory2: "LahijVillageMinihistory2",
      titleDescitemTop: "LahijVillageTitleDescitemTop",
      titleDescitemTopOpis: "LahijVillageTitleDescitemTopOpis",
      position: [40.84681636792118, 48.38518377144627],
    },
    // Nature Karabakh
    {
      img: KarabaxNature,
      descImgMain: KarabaxMain,
      DescFirstHeydar: KarabaxDesc,
      id: 54,
      special: "nature",
      specialization: "nature",
      name: "KarabakhMountainsName",
      openClose: "KarabakhMountainsOpenClose",
      timeBuild: "KarabakhMountainsTimeBuild",
      adres: "KarabakhMountainsAdres",
      cost: "KarabakhMountainsCost",
      rooms: "KarabakhMountainsRooms",
      sayt: "KarabakhMountainsSayt",
      category: "Qarabağ",
      city: "Karabakh",
      specialTranslate: "nature",
      minihistory: "KarabakhMountainsMinihistory",
      minihistory2: "KarabakhMountainsMinihistory2",
      titleDescitemTop: "KarabakhMountainsTitleDescitemTop",
      titleDescitemTopOpis: "KarabakhMountainsTitleDescitemTopOpis",
      position: [40.93823065869859, 49.10371939515798],
    },
    {
      img: LankaranNature,
      descImgMain: LankaranGizilMain,
      DescFirstHeydar: LankaranGizilDesc,
      id: 55,
      special: "nature",
      specialization: "nature",
      name: "GizilAghajName",
      openClose: "GizilAghajOpenClose",
      timeBuild: "GizilAghajTimeBuild",
      adres: "GizilAghajAdres",
      cost: "GizilAghajCost",
      rooms: "GizilAghajRooms",
      sayt: "-",
      category: "Lənkəran",
      city: "Lankaran",
      specialTranslate: "nature",
      minihistory: "GizilAghajMinihistory",
      minihistory2: "GizilAghajMinihistory2",
      titleDescitemTop: "GizilAghajTitleDescitemTop",
      titleDescitemTopOpis: "GizilAghajTitleDescitemTopOpis",
      position: [39.170660766035724, 48.9128710925049],
    },
    {
      img: YanardagNature,
      descImgMain: YanardagMainNature,
      DescFirstHeydar: YanardagDescNature,
      id: 56,
      special: "nature",
      specialization: "nature",
      name: "YanarDagName",
      openClose: "YanarDagOpenClose",
      timeBuild: "YanarDagTimeBuild",
      adres: "YanarDagAdres",
      cost: "YanarDagCost",
      rooms: "YanarDagRooms",
      sayt: "YanarDagSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "nature",
      minihistory: "YanarDagMinihistory",
      minihistory2: "YanarDagMinihistory2",
      titleDescitemTop: "YanarDagTitleDescitemTop",
      titleDescitemTopOpis: "YanarDagTitleDescitemTopOpis",
      position: [40.502643160522155, 49.89090663408132],
    },
    {
      img: AfrudjaNature,
      descImgMain: AfrudjaMainNature,
      DescFirstHeydar: AfrudjaDescNature,
      id: 57,
      special: "nature",
      specialization: "nature",
      name: "AfurdjaName",
      openClose: "AfurdjaOpenClose",
      timeBuild: "AfurdjaTimeBuild",
      adres: "AfurdjaAdres",
      cost: "AfurdjaCost",
      rooms: "AfurdjaRooms",
      sayt: "AfurdjaSayt",
      category: "Qarışıq yerlər",
      minihistory: "AfurdjaMinihistory",
      minihistory2: "AfurdjaMinihistory2",
      titleDescitemTop: "AfurdjaTitleDescitemTop",
      titleDescitemTopOpis: "AfurdjaTitleDescitemTopOpis",
      position: [41.156666827089175, 48.626316827866056],
    },
    {
      img: QusarSuniNature,
      descImgMain: QusarSuniMain,
      DescFirstHeydar: QusarSuinDesc,
      id: 58,
      special: "nature",
      specialization: "nature",
      name: "susinName",
      openClose: "susinOpenClose",
      timeBuild: "susinTimeBuild",
      adres: "susinAdres",
      cost: "susinCost",
      rooms: "susinRooms",
      sayt: "-",
      category: "Qarışıq yerlər",
      minihistory: "susinMinihistory1",
      minihistory2: "susinMinihistory2",
      titleDescitemTop: "susinTitleTop",
      titleDescitemTopOpis: "susinTitleOpis",
      position: [41.29452908256198, 48.11085440675008],
    },
    {
      img: BeshbarmagNature,
      descImgMain: BeshbarmagMainNature,
      DescFirstHeydar: BeshbarmagDescNature,
      id: 59,
      special: "nature",
      specialization: "nature",
      name: "beshbarmagName",
      openClose: "beshbarmagOpenClose",
      timeBuild: "beshbarmagTimeBuild",
      adres: "beshbarmagAdres",
      cost: "beshbarmagCost",
      rooms: "beshbarmagRooms",
      category: "Qobustan",
      city: "Gobustan",
      specialTranslate: "nature",
      minihistory: "beshbarmagMiniHistory",
      minihistory2: "beshbarmagMiniHistory2",
      titleDescitemTop: "beshbarmagTitleDescTop",
      titleDescitemTopOpis: "beshbarmagTitleDescTopOpis",
      position: [40.931250224556756, 49.23564277242479],
    },
    {
      img: QusarLazaNature,
      descImgMain: QusarLazaMainNature,
      DescFirstHeydar: QusarLazaDescNature,
      id: 60,
      special: "nature",
      specialization: "nature",
      name: "lazaName",
      openClose: "lazaOpenClose",
      timeBuild: "lazaTimeBuild",
      adres: "lazaAdres",
      cost: "lazaCost",
      rooms: "lazaRooms",
      sayt: "lazaSayt",
      category: "Qarışıq yerlər",
      minihistory: "lazaMiniHistory1",
      minihistory2: "lazaMiniHistory2",
      titleDescitemTop: "lazaTitleTop",
      titleDescitemTopOpis: "lazaTitleOpis",
      position: [41.29322471030304, 48.116545435645456],
    },
    {
      img: MaralgolNature,
      descImgMain: MaralgolMainNature,
      DescFirstHeydar: MaralgolDescNature,
      id: 61,
      special: "nature",
      specialization: "nature",
      name: "maralgolName",
      openClose: "maralgolOpenClose",
      timeBuild: "maralgolTimeBuild",
      adres: "maralgolAdres",
      cost: "maralgolCost",
      rooms: "maralgolRooms",
      sayt: "maralgolSayt",
      category: "Gəncə",
      city: "Ganja",
      specialTranslate: "nature",
      minihistory: "maralgolMiniHistory1",
      minihistory2: "maralgolMiniHistory2",
      titleDescitemTop: "maralgolTitleTop",
      titleDescitemTopOpis: "maralgolTitleOpis",
      position: [40.37644440769853, 46.312785828832865],
    },
    {
      img: QabalaNature,
      descImgMain: QabalaYeddiMainNature,
      DescFirstHeydar: QabalaYeddiDescNature,
      id: 62,
      special: "nature",
      specialization: "nature",
      name: "yeddigozelName",
      openClose: "yeddigozelOpenClose",
      timeBuild: "yeddigozelTimeBuild",
      adres: "yeddigozelAdres",
      cost: "yeddigozelCost",
      rooms: "yeddigozelRooms",
      sayt: "-",
      category: "Qəbələ",
      city: "Gabala",
      specialTranslate: "nature",
      minihistory: "yeddigozelMiniHistory1",
      minihistory2: "yeddigozelMiniHistory2",
      titleDescitemTop: "yeddigozelTitleTop",
      titleDescitemTopOpis: "yeddigozelTitleOpis",
      position: [40.9769265788676, 47.91395824901245],
    },
    {
      img: QizilBashNature,
      descImgMain: QizilbashMainNature,
      DescFirstHeydar: QizalbashDescNature,
      id: 63,
      special: "nature",
      specialization: "nature",
      name: "gizilbashName",
      adres: "gizilbashOpenClose",
      openClose: "gizilbashTimeBuild",
      timeBuild: "gizilbashAdres",
      cost: "gizilbashCost",
      rooms: "gizilbashRooms",
      sayt: "-",
      category: "Şamaxı",
      city: "Shamakhi",
      specialTranslate: "nature",
      minihistory: "gizilbashMiniHistory1",
      minihistory2: "gizilbashMiniHistory2",
      titleDescitemTop: "gizilbashTitleTop",
      titleDescitemTopOpis: "gizilbashTitleOpis",
      position: [40.64474701428576, 48.67181281267531],
    },
    {
      img: TangiyatiNature,
      descImgMain: TangiyatiMainNature,
      DescFirstHeydar: TangiyatiDescNature,
      id: 64,
      special: "nature",
      specialization: "nature",
      name: "tengyaltiName",
      adres: "tengyaltiAdres",
      openClose: "tengyaltiOpenClose",
      timeBuild: "tengyaltiTimeBuild",
      cost: "tengyaltiCost",
      rooms: "tengyaltiRooms",
      sayt: "-",
      category: "Qarışıq yerlər",
      city: "Lerik",
      specialTranslate: "nature",
      minihistory: "tengyaltiMiniHistory1",
      minihistory2: "tengyaltiMiniHistory2",
      titleDescitemTop: "tengyaltiTitleTop",
      titleDescitemTopOpis: "tengyaltiTitleOpis",
      position: [41.290574016422866, 48.071833721743076],
    },
    // Park
    {
      img: HighPark,
      descImgMain: HighParkMain,
      DescFirstHeydar: HighParkFunikler,
      DescSecondImg: HighParkFunikler,
      id: 65,
      special: "attractive",
      specialization: "Attractive",
      name: "Highland Park",
      openClose: "Круглосуточна",
      timeBuild: "построен с 1935 г., реконструирован в 2011–2013 гг.",
      adres: "Highland Park/Alley of Martyrs",
      cost: "1 AZN",
      rooms: "Количество выставочных залов: 5",
      sayt: "-",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory:
        "Вот подробный обзор Highland Park (Нагорный парк / Dağüstü Park) и смотровой площадки — одного из самых впечатляющих и значимых мест в Баку:",
      minihistory2:
        "Он предлагает изумительные панорамные виды на Каспийское море, Пламенные башни, набережную Баку, Старый город (Ичери‑Шехер), дворец Ширваншахов и бухту",
      titleDescitemTop: "Нагорный парк — сердце Баку с видом в вечность",
      titleDescitemTopOpis:
        "Высоко над шумными улицами, где город сменяет суету на тишину, раскинулся Нагорный парк — живописное и символичное место, где история, природа и архитектура переплетаются в одной гармонии. Здесь дыхание Баку становится особенно лёгким, а взгляд — особенно дальним. Это не просто парк. Это — вид на душу города.Прогуливаясь по тенистым аллеям Нагорного парка, ты словно попадаешь в другой Баку — спокойный, созерцательный, наполненный светом и смыслом. Здесь растут стройные кипарисы, пальмы и ухоженные клумбы, поют птицы, шепчет ветер… . С каждым шагом ты поднимаешься выше — к самой вершине города, где тебя встречают лучшие панорамы столицы: сверкающий Каспий, Приморский бульвар, Пламенные башни, Старый город и бескрайнее небо.",
      titleDescitemBottom: "Бакинский фуникулёр — путь в небо над городом",
      titleDescitembottomOpis:
        "Представь: шумный Баку остаётся внизу, а ты плавно поднимаешься всё выше и выше, будто скользишь по невидимой нити в небеса. Перед тобой открываются завораживающие панорамы города, Каспий переливается золотом заката, а сердце замирает от красоты. Всё это — Бакинский фуникулёр, единственный в своём роде в Азербайджане и настоящий символ романтики, ностальгии и духа времени. Бакинский фуникулёр был открыт ещё в 1960 году и стал первым в Закавказье. С тех пор он не раз модернизировался, но сохранил свою душу — тот самый неспешный ритм, мягкое движение и завораживающее ощущение перехода из повседневности в волшебство. Во время подъёма кажется, что ты перемещаешься сквозь времена — от исторических улиц центра до мемориальной Аллеи Шехидов, туда, где воздух чище, а мысли светлее.",
    },
    {
      img: ShamaxiMedrese,
      descImgMain: ShamaxiMedreseMain,
      DescFirstHeydar: ShamaxiMedreseDesc2,
      id: 66,
      special: "Palaces",
      specialization: "Дворцы",
      name: "shamakhiMosqueName",
      openClose: "shamakhiMosqueOpenClose",
      timeBuild: "shamakhiMosqueTimeBuild",
      adres: "shamakhiMosqueAdres",
      cost: "shamakhiMosqueCost",
      rooms: "shamakhiMosqueRooms",
      sayt: "-",
      category: "Şamaxı",
      city: "Shamakhi",
      specialTranslate: "palaces",
      minihistory: "shamakhiMosqueMinihistory",
      minihistory2: "shamakhiMosqueMinihistory2",
      titleDescitemTop: "shamakhiMosqueTitleDescitemTop",
      titleDescitemTopOpis: "shamakhiMosqueTitleDescitemTopOpis",
      position: [40.62705871299343, 48.6438404394922],
    },
    {
      img: Diribaba,
      descImgMain: DiriBabaMain,
      DescFirstHeydar: DiriBabaDesc,
      id: 67,
      special: "Palaces",
      specialization: "Дворцы",
      name: "diriBabaName",
      openClose: "diriBabaOpenClose",
      timeBuild: "diriBabaTimeBuild",
      adres: "diriBabaAdres",
      cost: "diriBabaCost",
      rooms: "diriBabaRooms",
      sayt: "-",
      category: "Qobustan",
      city: "Gobustan",
      specialTranslate: "palaces",
      minihistory: "diriBabaMinihistory",
      minihistory2: "diriBabaMinihistory2",
      titleDescitemTop: "diriBabaTitleDescTop",
      titleDescitemTopOpis: "diriBabaTitleDescOpis",
      position: [40.53268767733051, 48.942051083664715],
    },
    {
      img: QobustanQorgu,
      descImgMain: QobustanQorguMain,
      DescFirstHeydar: QobustanQorguDesc,
      id: 68,
      special: "Palaces",
      specialization: "Дворцы",
      name: "qobustanName",
      openClose: "qobustanOpenClose",
      timeBuild: "qobustanTimeBuild",
      adres: "qobustanAdres",
      cost: "qobustanCost",
      rooms: "qobustanRooms",
      sayt: "http://gobustan-rockart.az",
      category: "Qobustan",
      city: "Gobustan",
      specialTranslate: "palaces",
      minihistory: "qobustanMinihistory",
      minihistory2: "qobustanMinihistory2",
      titleDescitemTop: "qobustanTitleDescTop",
      titleDescitemTopOpis: "qobustanTitleDescOpis",
      position: [40.111552740767294, 49.37840755481291],
    },
    {
      img: QobustanVolcano,
      descImgMain: QobustanVolcanoMain,
      DescFirstHeydar: QobustanVolcanoDesc,
      id: 69,
      special: "nature",
      specialization: "Природный объект",
      name: "QobustanVolcanoName",
      openClose: "QobustanVolcanoOpenClose",
      timeBuild: "QobustanVolcanoTimeBuild",
      adres: "QobustanVolcanoAdres",
      cost: "QobustanVolcanoCost",
      rooms: "QobustanVolcanoRooms",
      sayt: "https://azerbaijan.travel/mud-volcanoes",
      category: "Qobustan",
      city: "Gobustan",
      specialTranslate: "palaces",
      minihistory: "QobustanVolcanoMiniHistory1",
      minihistory2: "QobustanVolcanoMiniHistory2",
      titleDescitemTop: "QobustanVolcanoTitle",
      titleDescitemTopOpis: "QobustanVolcanoOpis",
      position: [40.237438793414135, 49.12652471337856],
    },
    {
      img: ShekiWall,
      descImgMain: ShekiWallMain,
      DescFirstHeydar: ShekiWallDesc,
      id: 70,
      special: "Palaces",
      specialization: "Дворцы",
      name: "ShekiFortressName",
      openClose: "ShekiFortressOpenClose",
      timeBuild: "ShekiFortressTimeBuild",
      adres: "ShekiFortressAdres",
      cost: "ShekiFortressCost",
      rooms: "ShekiFortressRooms",
      sayt: "-",
      category: "Şəki",
      city: "Sheki",
      specialTranslate: "palaces",
      minihistory: "ShekiFortressMiniHistory1",
      minihistory2: "ShekiFortressMiniHistory2",
      titleDescitemTop: "ShekiFortressTitleDesc",
      titleDescitemTopOpis: "ShekiFortressTitleDescOpis",
      position: [41.20379452981041, 47.19687165488616],
    },
    {
      img: SekiAlbani,
      descImgMain: SekiAlbaniMain,
      DescFirstHeydar: SekiAlbaniDesc,
      id: 71,
      special: "Palaces",
      specialization: "Дворцы",
      name: "KishTempleName",
      openClose: "KishTempleOpenClose",
      timeBuild: "KishTempleTimeBuild",
      adres: "KishTempleAdres",
      cost: "KishTempleCost",
      rooms: "KishTempleRooms",
      sayt: "-",
      category: "Şəki",
      city: "Sheki",
      specialTranslate: "palaces",
      minihistory: "KishTempleMiniHistory1",
      minihistory2: "KishTempleMiniHistory2",
      titleDescitemTop: "KishTempleTitleDesc",
      titleDescitemTopOpis: "KishTempleTitleDescOpis",
      position: [41.249136101495004, 47.193104937670235],
    },
    {
      img: SekiXanMosque,
      descImgMain: SekiXanMosqueMain,
      DescFirstHeydar: SekiXanMosqueDesc,
      id: 72,
      special: "Palaces",
      specialization: "Дворцы",
      name: "ShekiKhanMosqueName",
      openClose: "ShekiKhanMosqueOpenClose",
      timeBuild: "ShekiKhanMosqueTimeBuild",
      adres: "ShekiKhanMosqueAdres",
      cost: "ShekiKhanMosqueCost",
      rooms: "ShekiKhanMosqueRooms",
      sayt: "-",
      category: "Şəki",
      city: "Sheki",
      specialTranslate: "palaces",
      minihistory: "ShekiKhanMosqueMiniHistory1",
      minihistory2: "ShekiKhanMosqueMiniHistory2",
      titleDescitemTop: "ShekiKhanMosqueTitleDesc",
      titleDescitemTopOpis: "ShekiKhanMosqueTitleDescOpis",
      position: [41.202899642892994, 47.19209264136206],
    },
    {
      img: ShekiMehemmed,
      descImgMain: ShekiMehemmedMain,
      DescFirstHeydar: ShekiMehemmedDesc,
      id: 73,
      special: "Palaces",
      specialization: "Дворцы",
      name: "SheikhMuhammadMosqueName",
      openClose: "SheikhMuhammadMosqueOpenClose",
      timeBuild: "SheikhMuhammadMosqueTimeBuild",
      adres: "SheikhMuhammadMosqueAdres",
      cost: "SheikhMuhammadMosqueCost",
      rooms: "SheikhMuhammadMosqueRooms",
      sayt: "-",
      category: "Ismayilli",
      city: "Ismailli",
      specialTranslate: "palaces",
      minihistory: "SheikhMuhammadMosqueMiniHistory1",
      minihistory2: "SheikhMuhammadMosqueMiniHistory2",
      titleDescitemTop: "SheikhMuhammadMosqueTitleDesc",
      titleDescitemTopOpis: "SheikhMuhammadMosqueTitleDescOpis",
      position: [40.75627878500051, 48.389916526003226],
    },
    {
      img: AsmaKorpusu,
      descImgMain: AsmaKorpusuMain,
      DescFirstHeydar: AsmaKorpusuDesc,
      id: 74,
      special: "Palaces",
      specialization: "Дворцы",
      name: "HangingBridgeName",
      openClose: "HangingBridgeOpenClose",
      timeBuild: "HangingBridgeTimeBuild",
      adres: "HangingBridgeAdres",
      cost: "HangingBridgeCost",
      rooms: "HangingBridgeRooms",
      sayt: "-",
      category: "Ismayilli",
      city: "Ismailli",
      specialTranslate: "palaces",
      minihistory: "HangingBridgeMiniHistory1",
      minihistory2: "HangingBridgeMiniHistory2",
      titleDescitemTop: "HangingBridgeTitleDesc",
      titleDescitemTopOpis: "HangingBridgeTitleDescOpis",
      position: [41.21512948963729, 47.36751847648517],
    },
    {
      img: LakeSide,
      descImgMain: LakeSideMain,
      DescFirstHeydar: LakeSideDesc,
      id: 75,
      special: "attractive",
      specialization: "Attractive",
      name: "LakesideGardenName",
      openClose: "LakesideGardenOpenClose",
      timeBuild: "LakesideGardenTimeBuild",
      adres: "LakesideGardenAdres",
      cost: "LakesideGardenCost",
      rooms: "LakesideGardenRooms",
      sayt: "-",
      category: "Ismayilli",
      city: "Ismailli",
      specialTranslate: "Entertainment",
      minihistory: "LakesideGardenMiniHistory1",
      minihistory2: "LakesideGardenMiniHistory2",
      titleDescitemTop: "LakesideGardenTitleDesc",
      titleDescitemTopOpis: "LakesideGardenTitleDescOpis",
      position: [40.74684561228057, 48.261775470179096],
    },
    {
      img: Xanqizi,
      descImgMain: XanqiziMain,
      DescFirstHeydar: XanqiziDesc,
      id: 76,
      special: "Palaces",
      specialization: "Дворцы",
      name: "KhanGiziSpringName",
      openClose: "KhanGiziSpringOpenClose",
      timeBuild: "KhanGiziSpringTimeBuild",
      adres: "KhanGiziSpringAdres",
      cost: "KhanGiziSpringCost",
      rooms: "KhanGiziSpringRooms",
      sayt: "-",
      category: "Qarabağ",
      city: "Karabakh",
      specialTranslate: "palaces",
      minihistory: "KhanGiziSpringMiniHistory1",
      minihistory2: "KhanGiziSpringMiniHistory2",
      titleDescitemTop: "KhanGiziSpringTitleDesc",
      titleDescitemTopOpis: "KhanGiziSpringTitleDescOpis",
      position: [39.764353924620025, 46.75102986829353],
    },
    {
      img: SushaQala,
      descImgMain: SushaQalaMain,
      DescFirstHeydar: SushaQalaDesc,
      id: 77,
      special: "Palaces",
      specialization: "Дворцы",
      name: "ShushaFortressName",
      openClose: "ShushaFortressOpenClose",
      timeBuild: "ShushaFortressTimeBuild",
      adres: "ShushaFortressAdres",
      cost: "ShushaFortressCost",
      rooms: "ShushaFortressRooms",
      sayt: "-",
      category: "Qarabağ",
      city: "Karabakh",
      specialTranslate: "palaces",
      minihistory: "ShushaFortressMiniHistory1",
      minihistory2: "ShushaFortressMiniHistory2",
      titleDescitemTop: "ShushaFortressTitleDesc",
      titleDescitemTopOpis: "ShushaFortressTitleDescOpis",
      position: [39.765883215474034, 46.750247710622865],
    },
    {
      img: AlmanCirch,
      descImgMain: AlmanCirchMain,
      DescFirstHeydar: AlmanCirchDesc,
      id: 78,
      special: "Palaces",
      specialization: "Дворцы",
      name: "ShamkirLutheranChurchName",
      openClose: "ShushaFortressOpenClose",
      timeBuild: "ShushaFortressTimeBuild",
      adres: "ShamkirLutheranChurchAdres",
      cost: "ShamkirLutheranChurchCost",
      rooms: "ShamkirLutheranChurchRooms",
      sayt: "-",
      category: "Şəmkir",
      city: "Shamkir",
      specialTranslate: "palaces",
      minihistory: "ShamkirLutheranChurchMiniHistory1",
      minihistory2: "ShamkirLutheranChurchMiniHistory2",
      titleDescitemTop: "ShamkirLutheranChurchTitleDesc",
      titleDescitemTopOpis: "ShamkirLutheranChurchTitleDescOpis",
      position: [40.89686894766994, 46.045607822172705],
    },
    {
      img: YeddiQunbez,
      descImgMain: YeddiQunbezMain,
      DescFirstHeydar: YeddiQunbezDesc,
      id: 79,
      special: "Palaces",
      specialization: "Дворцы",
      name: "YeddiGunbezName",
      openClose: "YeddiGunbezOpenClose",
      timeBuild: "YeddiGunbezTimeBuild",
      adres: "YeddiGunbezAdres",
      cost: "YeddiGunbezCost",
      rooms: "YeddiGunbezRooms",
      sayt: "-",
      category: "Şamaxı",
      city: "Shamakhi",
      specialTranslate: "nature",
      minihistory: "YeddiGunbezMiniHistory1",
      minihistory2: "YeddiGunbezMiniHistory2",
      titleDescitemTop: "YeddiGunbezTitleDesc",
      titleDescitemTopOpis: "YeddiGunbezTitleDescOpis",
      position: [40.620336574078415, 48.636215243192225],
    },
    {
      img: Pirqulu,
      descImgMain: PirquluMain,
      DescFirstHeydar: PirquliDesc,
      id: 80,
      special: "nature",
      specialization: "nature",
      name: "PirquluQoruguName",
      openClose: "PirquluQoruguOpenClose",
      timeBuild: "PirquluQoruguTimeBuild",
      adres: "PirquluQoruguAdres",
      cost: "PirquluQoruguCost",
      rooms: "PirquluQoruguRooms",
      sayt: "-",
      category: "Şamaxı",
      city: "Shamakhi",
      specialTranslate: "nature",
      minihistory: "PirquluQoruguMiniHistory1",
      minihistory2: "PirquluQoruguMiniHistory2",
      titleDescitemTop: "PirquluQoruguTitleDesc",
      titleDescitemTopOpis: "PirquluQoruguTitleDescOpis",
      position: [40.783643975301764, 48.51155255484585],
    },
    {
      img: ShamkirCastle,
      descImgMain: ShamkirCastleMain,
      DescFirstHeydar: ShamkirCastleDesc,
      id: 81,
      special: "Palaces",
      specialization: "Дворцы",
      name: "ShamkirCastleName",
      openClose: "ShamkirCastleOpenClose",
      timeBuild: "ShamkirCastleTimeBuild",
      adres: "ShamkirCastleAdres",
      cost: "ShamkirCastleCost",
      rooms: "ShamkirCastleRooms",
      sayt: "-",
      category: "Şəmkir",
      city: "Shamkir",
      specialTranslate: "palaces",
      minihistory: "ShamkirCastleMiniHistory1",
      minihistory2: "ShamkirCastleMiniHistory2",
      titleDescitemTop: "ShamkirCastleTitleDesc",
      titleDescitemTopOpis: "ShamkirCastleTitleDescOpis",
      position: [40.83526406735779, 46.048628869228516],
    },
    {
      img: ZooPark,
      descImgMain: ZooParkMain,
      DescFirstHeydar: ZooParkDesc,
      id: 82,
      special: "attractive",
      specialization: "Attractive",
      name: "BakuZooName",
      openClose: "BakuZooOpenClose",
      timeBuild: "BakuZooTimeBuild",
      adres: "BakuZooAdres",
      cost: "BakuZooCost",
      rooms: "BakuZooRooms",
      sayt: "BakuZooSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "BakuZooMiniHistory1",
      minihistory2: "BakuZooMiniHistory2",
      titleDescitemTop: "BakuZooTitleDesc",
      titleDescitemTopOpis: "BakuZooTitleDescOpis",
      position: [40.392141055893696, 49.84909528365926],
    },
    {
      img: TofigStadion,
      descImgMain: TofigStadionMain,
      DescFirstHeydar: TofigStadionDesc,
      id: 83,
      special: "attractive",
      specialization: "Attractive",
      name: "TofiqStadiumName",
      openClose: "TofiqStadiumOpenClose",
      timeBuild: "TofiqStadiumTimeBuild",
      adres: "TofiqStadiumAdres",
      cost: "TofiqStadiumCost",
      rooms: "TofiqStadiumRooms",
      sayt: "TofiqStadiumSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "TofiqStadiumMiniHistory1",
      minihistory2: "TofiqStadiumMiniHistory2",
      titleDescitemTop: "TofiqStadiumTitleDesc",
      titleDescitemTopOpis: "TofiqStadiumTitleDescOpis",
      position: [40.39751319829478, 49.852371381812496],
    },
    {
      img: OlympicStadion,
      descImgMain: OlympicStadionMain,
      DescFirstHeydar: OlympicStadionDesc,
      id: 84,
      special: "attractive",
      specialization: "Attractive",
      name: "BakuOlympicStadiumName",
      openClose: "BakuOlympicStadiumOpenClose",
      timeBuild: "BakuOlympicStadiumTimeBuild",
      adres: "BakuOlympicStadiumAdres",
      cost: "BakuOlympicStadiumCost",
      rooms: "BakuOlympicStadiumRooms",
      sayt: "BakuOlympicStadiumSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "BakuOlympicStadiumMiniHistory1",
      minihistory2: "BakuOlympicStadiumMiniHistory2",
      titleDescitemTop: "BakuOlympicStadiumTitleDesc",
      titleDescitemTopOpis: "BakuOlympicStadiumTitleDescOpis",
      position: [40.430226436944736, 49.91937968623389],
    },
    {
      img: HeydarAliyevArenaStadion,
      descImgMain: HeydarAliyevArenaStadionMain,
      DescFirstHeydar: HeydarAliyevArenaStadionDesc,
      id: 85,
      special: "attractive",
      specialization: "Attractive",
      name: "HeydarAliyevArenaName",
      openClose: "HeydarAliyevArenaOpenClose",
      timeBuild: "HeydarAliyevArenaTimeBuild",
      adres: "HeydarAliyevArenaAdres",
      cost: "HeydarAliyevArenaCost",
      rooms: "HeydarAliyevArenaRooms",
      sayt: "HeydarAliyevArenaSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "HeydarAliyevArenaMiniHistory1",
      minihistory2: "HeydarAliyevArenaMiniHistory2",
      titleDescitemTop: "HeydarAliyevArenaTitleDesc",
      titleDescitemTopOpis: "HeydarAliyevArenaTitleDescOpis",
      position: [40.391964154202995, 49.825246345925784],
    },
    {
      img: BakuCrystalHall,
      descImgMain: BakuCrystalHallMain,
      DescFirstHeydar: BakuCrystalHallDesc,
      id: 86,
      special: "attractive",
      specialization: "Attractive",
      name: "BakuCrystalHallName",
      openClose: "BakuCrystalHallOpenClose",
      timeBuild: "BakuCrystalHallTimeBuild",
      adres: "BakuCrystalHallAdres",
      cost: "BakuCrystalHallCost",
      rooms: "BakuCrystalHallRooms",
      sayt: "BakuCrystalHallSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "BakuCrystalHallMiniHistory1",
      minihistory2: "BakuCrystalHallMiniHistory2",
      titleDescitemTop: "BakuCrystalHallTitleDesc",
      titleDescitemTopOpis: "BakuCrystalHallTitleDescOpis",
      position: [40.34431920634967, 49.85029422968052],
    },
    {
      img: BakuSportsHall,
      descImgMain: BakuSportsHallMain,
      DescFirstHeydar: BakuSportsHallDesc,
      id: 87,
      special: "attractive",
      specialization: "Attractive",
      name: "BakuSportsHallName",
      openClose: "BakuSportsHallOpenClose",
      timeBuild: "BakuSportsHallTimeBuild",
      adres: "BakuSportsHallAdres",
      cost: "BakuSportsHallCost",
      rooms: "BakuSportsHallRooms",
      sayt: "BakuSportsHallSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "BakuSportsHallMiniHistory1",
      minihistory2: "BakuSportsHallMiniHistory2",
      titleDescitemTop: "BakuSportsHallTitleDesc",
      titleDescitemTopOpis: "BakuSportsHallTitleDescOpis",
      position: [40.35886834853206, 49.83495281065738],
    },
    {
      img: QizQalasi,
      descImgMain: QizQalasiMain,
      DescFirstHeydar: QizQalasiDesc,
      id: 88,
      special: "Palaces",
      specialization: "Дворцы",
      name: "QizQalasiName",
      openClose: "QizQalasiOpenClose",
      timeBuild: "QizQalasiTimeBuild",
      adres: "QizQalasiAdres",
      cost: "QizQalasiCost",
      rooms: "QizQalasiRooms",
      sayt: "-",
      category: "Bakı",
      city: "baku",
      specialTranslate: "palaces",
      minihistory: "QizQalasiMiniHistory1",
      minihistory2: "QizQalasiMiniHistory2",
      titleDescitemTop: "QizQalasiTitleDesc",
      titleDescitemTopOpis: "QizQalasiTitleDescOpis",
      position: [40.36628644015691, 49.83716026647034],
    },
    {
      img: BakuYachtClub,
      descImgMain: BakuYachtClubMain,
      DescFirstHeydar: BakuYachtClubDesc,
      id: 89,
      special: "attractive",
      specialization: "Attractive",
      name: "BakuYachtClubName",
      openClose: "BakuYachtClubOpenClose",
      timeBuild: "BakuYachtClubTimeBuild",
      adres: "BakuYachtClubAdres",
      cost: "BakuYachtClubCost",
      rooms: "BakuYachtClubRooms",
      sayt: "BakuYachtClubSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "BakuYachtClubMiniHistory1",
      minihistory2: "BakuYachtClubMiniHistory2",
      titleDescitemTop: "BakuYachtClubTitleDesc",
      titleDescitemTopOpis: "BakuYachtClubTitleDescOpis",
      position: [40.36212878491072, 49.840247496285144],
    },
    {
      img: PhilharmonicGarden,
      descImgMain: PhilharmonicGardenMain,
      DescFirstHeydar: PhilharmonicGardenDesc,
      id: 90,
      special: "Palaces",
      specialization: "Дворцы",
      name: "PhilharmonicGardenName",
      openClose: "PhilharmonicGardenOpenClose",
      timeBuild: "PhilharmonicGardenTimeBuild",
      adres: "PhilharmonicGardenAdres",
      cost: "PhilharmonicGardenCost",
      rooms: "PhilharmonicGardenRooms",
      sayt: "-",
      category: "Bakı",
      city: "baku",
      specialTranslate: "palaces",
      minihistory: "PhilharmonicGardenMiniHistory1",
      minihistory2: "PhilharmonicGardenMiniHistory2",
      titleDescitemTop: "PhilharmonicGardenTitleDesc",
      titleDescitemTopOpis: "PhilharmonicGardenTitleDescOpis",
      position: [40.36342632925949, 49.83396557640743],
    },
    {
      img: FlameTowers,
      descImgMain: FlameTowersMain,
      DescFirstHeydar: FlameTowersDesc,
      id: 91,
      special: "Palaces",
      specialization: "Дворцы",
      name: "FlameTowersName",
      openClose: "FlameTowersOpenClose",
      timeBuild: "FlameTowersTimeBuild",
      adres: "FlameTowersAdres",
      cost: "FlameTowersCost",
      rooms: "FlameTowersRooms",
      sayt: "-",
      category: "Bakı",
      city: "baku",
      specialTranslate: "palaces",
      minihistory: "FlameTowersMiniHistory1",
      minihistory2: "FlameTowersMiniHistory2",
      titleDescitemTop: "FlameTowersTitleDesc",
      titleDescitemTopOpis: "FlameTowersTitleDescOpis",
      position: [40.359669813739494, 49.826757566426984],
    },
    {
      img: GulustanPalace,
      descImgMain: GulustanPalaceMain,
      DescFirstHeydar: GulustanPalaceDesc,
      id: 92,
      special: "Palaces",
      specialization: "Дворцы",
      name: "GulustanPalaceName",
      openClose: "GulustanPalaceOpenClose",
      timeBuild: "GulustanPalaceTimeBuild",
      adres: "GulustanPalaceAdres",
      cost: "GulustanPalaceCost",
      rooms: "GulustanPalaceRooms",
      sayt: "-",
      category: "Bakı",
      city: "baku",
      specialTranslate: "palaces",
      minihistory: "GulustanPalaceMiniHistory1",
      minihistory2: "GulustanPalaceMiniHistory2",
      titleDescitemTop: "GulustanPalaceTitleDesc",
      titleDescitemTopOpis: "GulustanPalaceTitleDescOpis",
      position: [40.35874173764141, 49.83163838166029],
    },
    {
      img: LittleVenice,
      descImgMain: LittleVeniceMain,
      DescFirstHeydar: LittleVeniceDesc,
      id: 93,
      special: "attractive",
      specialization: "Attractive",
      name: "LittleVeniceName",
      openClose: "LittleVeniceOpenClose",
      timeBuild: "LittleVeniceTimeBuild",
      adres: "LittleVeniceAdres",
      cost: "LittleVeniceCost",
      rooms: "LittleVeniceRooms",
      sayt: "LittleVeniceSayt",
      category: "Bakı",
      city: "baku",
      specialTranslate: "Entertainment",
      minihistory: "LittleVeniceMiniHistory1",
      minihistory2: "LittleVeniceMiniHistory2",
      titleDescitemTop: "LittleVeniceTitleDesc",
      titleDescitemTopOpis: "LittleVeniceTitleDescOpis",
      position: [40.361216578915716, 49.83584255890647],
    },
    {
      img: WarTrophiesPark,
      descImgMain: WarTrophiesParkMain,
      DescFirstHeydar: WarTrophiesParkDesc,
      id: 94,
      special: "museums",
      name: "WarTrophiesParkName",
      openClose: "WarTrophiesParkOpenClose",
      timeBuild: "WarTrophiesParkTimeBuild",
      adres: "WarTrophiesParkAdres",
      cost: "WarTrophiesParkCost",
      rooms: "WarTrophiesParkRooms",
      sayt: "saytYarat",
      category: "Bakı",
      city: "baku",
      specialTranslate: "museums",
      specialization: "Музей",
      minihistory: "WarTrophiesParkMiniHistory1",
      minihistory2: "WarTrophiesParkMiniHistory2",
      titleDescitemTop: "WarTrophiesParkTitleDesc",
      titleDescitemTopOpis: "WarTrophiesParkTitleDescOpis",
      position: [40.37645892318365, 49.874246141959915],
    },
  ];

  const [season, setSeason] = useState([]);

  const addToDesc = (product) => {
    setSeason([{ ...product, postId: 1 }]);
  };

  const SeasonData = [
    {
      id: 1,
      img: GS,
      postId: 1,
      name: "Габала",
      title: "Чeм интересен путешествие в Габалу",
    },
    { id: 2, img: NS, postId: 1, name: "Набран" },
    { id: 3, img: SHS, postId: 1, name: "Шеки" },
    { id: 4, img: SHW, postId: 3, name: "Шахдаг" },
    { id: 5, img: TufWin, postId: 3, name: "Туфандаг" },
    { id: 6, img: HinWin, postId: 3, name: "Хыналыг" },
    { id: 7, img: SS, postId: 2, name: "Шеки" },
    { id: 8, img: SG, postId: 2, name: "Гах" },
    { id: 9, img: Ls, postId: 2, name: "Лерик" },
  ];

  const [language, setLanguage] = useState("az");
  const handleLanguageChange = (event) => {
    setLanguage(event.target.value);
  };

  return (
    <MyContext.Provider
      value={{
        handleLanguageChange,
        language,
        translations,
        punktMenu,
        museums,
        traveled,
        SeasonData,
        addToDesc,
        season,
      }}
    >
      {children}
    </MyContext.Provider>
  );
};

export const useMyContext = () => {
  const context = useContext(MyContext);
  if (!context) {
    throw new Error("useMyContext должен использоваться внутри MyProvider");
  }
  return context;
};
